### ISSUE TITLE
Forbedring af kommunikation

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#100]
# Løser 5 i acceptkriterier
# Løser 6 i acceptkriterier
# Løser 49 i acceptkriterier

- [x] Nyhedsbreve under "Sendte" skal ikke kunne rettes eller sendes på ny (disabled)
- [x] Nyhedsbreve under "Sendte" skal kunne kopieres til ny kladde
- [x] Holdchat. Til korte beskeder på holdet. En ændring er, at arrangører skal kunne deltage i holdchat. 
- [x] Gruppechat. Skal fungere som i dag. 
- [x] Besked. Kortfattede beskeder. Minder om SMS. Kan ikke besvares. 
- [x] Nyhedsbrev skal kunne sendes til udvalgte administratorer 
- [x] Nyhedsbrev skal kunne sendes til hold, grupper, vagter og udvalgte brugere
- [x] Nyhedsbrev skal kunne sendes til ventelister
- [x] Der laves en senere segmenteringsmotor

Fælles for individuelle og kollektive nyhedsbreve er, at det er envejskommunikation, der ikke kan besvares. Brugerne instrueres i at inkludere deres kontakt-email adresse, så brugerne kan skrive tilbage dertil.

**Comment by mikkelsl** [comment]
De her er vel ret relaterede:
https://github.com/orgs/xooom-community/projects/2/views/2?pane=issue&itemId=60858420
https://github.com/orgs/xooom-community/projects/2?pane=issue&itemId=60856300

**Comment by MartinQwist** [comment]
Ift. acceptkriterier. Nyhedsbrevet her adresserer flere acceptkriterier, og bliver dermed en bredere beskedfunktion, som beskrives ovenfor. 

Den vedrør acceptkriterierne 5, 6 og 49.

**Comment by mikkelsl** [comment]
Løse tanker til at få den her konsolideret bedre.

Lige nu har vi:

- Notifikationer (SMS, email, push)
- Nyhedsbreve (email)

Notifikationer er korte beskeder uden formatering, der sendes under Vagter for et event/eventdato

Nyhedsbreve er lange beskeder med formatering, der sendes på sin egen side med segmenteringsmulighed som ovenfor

Vi bør nok slå de to sammen under et central begreb "Beskeder", hvor man kan håndtere begge dele, men hvor vi tydeliggør forskellen - måske vi endda helt skal fjerne muligheden for at sende beskeder under "Vagter" på et event.
