### ISSUE TITLE
Sorter opgaver i portal efter næstkommende vagt

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#102]
Det her bør sorteres efter, hvilken opgave der har næstkommende vagt:

https://ac.webbook.dk/proxy.php?proxy=forward_preview&module=system&v=6.2.7&b=DEV&context=attachments&id=12112&size=119026&md5=6d861d6c7013feedb2249ac6527ead8d&timestamp=2024-02-06+20%3A12%3A33&force=1

**Comment by MartinQwist** [comment]
Kan vi prioritere denne, hvis den er hurtig at lave? Logikken i rækkefølgen i visningen af opgaver/vagter på en eventside er ugennemskuelig. Vagter sorteres fint (tidligste kommende dato øverst) under hver vagt. 

Opgaverne bør ligeledes sorteres kronologisk. Øverste opgave skal vær den opgave, som har den tidligste næste eventdag - inklusiv dags dato.

Sådan ser det ud i dag: 
![Image](https://github.com/user-attachments/assets/6fca09d3-cde4-45f7-a8cf-d8129ef57d15)
