### ISSUE TITLE
Forbedring af holdchat

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#104]
- [x] Arrangør skal kunne deltage i holdchat.
- [x] Bedre tekstformatering - minimum linjeskift og aktive links. (også i gruppechat)
- [x] rel="noopener"

**Comment by MartinQwist** [comment]
Mut have: Linjeskift, aktive links. 

Shoould have: Evt. fed skrift, understreget, mv. Dette er ikke et must...

**Comment by mikkelsl** [comment]
Opgaven her lukker: https://ac.webbook.dk/projects/171?modal=Task-34293-171

**Comment by MartinQwist** [comment]
Relateret til #198
