### ISSUE TITLE
Se tidligere events på portal

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#113]
# Løser 1.3 i acceptkriterier

Mulighed for at kunne se tidligere events, der har været på portalen

**Comment by MartinQwist** [comment]
Kan nedprioriteres til fordel for Priority 1 i Volunteering.

**Comment by mikkelsl** [comment]
Hvis man går under Events i portalen, kan man vælge et filter med en dato bagud i tid for at finde tidligere events.
