### ISSUE TITLE
Tilføj krav om godkendelse på vagter

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#115]
# Løser 23.2 i acceptkriterier

Givet at der er oprettet et event i min organisation, når jeg opretter eller redigerer opgaver og vælger at et event kræver godkendelse, så vil alle fremtidige tilmeldinger fra frivillige skulle godkendes af min organisation.

# Løser 25.1 i acceptkriterier

Givet at en vagt er oprettet under en opgave med ansøgning, når en frivillig ansøger om vagten, når jeg som arrangør vælger at hhv. godkende eller afvise ansøgningen, så vil den frivillige blive hhv. tilmeldt vagten eller blive afvist.

Løsning:

- [x] Liste over vagtansøgninger (shiftRequests med status UNAPPROVED)
- [x] Godkend eller afvis vagtansøgning og send mailnotifikation ved godkend og afvis
- [x] Tag højde for eventindstilling i portal og opret henholdsvis Shift eller ShiftRequest, når en bruger anmoder om en vagt.
- [x] Antal vagtansøgninger count på forsiden (count shiftRequests med status UNAPPROVED)
- [x] Sørg for at shiftRequests med status UNAPPROVED ikke indgår i den automatiske afvikling af ventelisten
- [x] Der vælges per event om vagter kræver godkendelse, default er at det ikke kræver godkendelse
- [x] Lav migration

**Comment by MartinQwist** [comment]
Default skal være uden godkendelse for alle events.

**Comment by MartinQwist** [comment]
Kan nedprioriteres til fordel for Priority 1 i Volunteering.

**Comment by henrikbak** [comment]
@MartinQwist Fik du snakket med ReThinker om hvor indstillingen skulle ligge? Det kunne være en indstilling på organisationen, men det kunne også ligge længere nede på eventet eksempelvis.
