### ISSUE TITLE
Vagtstatus: godkendt fravær + udeblevet

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#117]
Det skal både være muligt for arrangør og holdleder at sætte status.

# Løser 35.1 i acceptkriterier
# Løser 36.1 i acceptkriterier

**Comment by MartinQwist** [comment]
Hvordan fungerer Fremmødt, Afbud og Udeblevet? 



![Image](https://github.com/xooom-community/product/assets/167326849/63dfe85d-c697-4102-a026-b339408b4ad9)

**Comment by mikkelsl** [comment]
Prøv igen, jeg lagde den over 5 minutter, før det var deployet. Havde ikke lige regnet med, at du var på 😄

**Comment by MartinQwist** [comment]
OK, den er løst. Det fungerer fint. Jeg accepterer. 

På sigt kunne det måske være fint at effketivisere Check in-operationerne, så de blev hurtigere. Ideer: mulighed for bulk actions i en samlet oversigt - f.eks. vagter, eller at man kan fremkalde en oversigt over alle frivillige alle dage. Nu tjekker man kun frivillige ind en enkelt vagtpakke ad gangen - og det kan være en lidt langsommelig proces. Man kunne også indøfre registrering via knap og ikke via menu som nu.

**Comment by mikkelsl** [comment]
Marker som fremmødt var faktisk en knap i listen tidligere netop af den grund.
Vi har også diskuteret løsningen med bulk action med checkboxes, helt enig i at det vil være en god ting at lave senere.

**Comment by MartinQwist** [comment]
En anden ting, jeg også tilføjer: De tre stati Fremmødt, Afbud, Udeblevet kan ikke bruges på mobilversion, som jo ellers er den mest oplagte indgang for vagtkoordinatorer.

**Comment by mikkelsl** [comment]
Det bør kun være Godkendt fravær, der ikke er tilgængelig for holdleder.

**Comment by MartinQwist** [comment]
Så vidt jeg kan se, så fremgår kravet om markering af alle tre vagtstati for vagtkoordinatorer af 36.1 (og det er fortsat VAAs ønske). Dette er så vidt jeg kan se en forudsætning for kriterie 36.1, som lyder: Givet at jeg er arrangør eller vagtkoordinator på et event med frivillige tilmeldt vagter og givet at tjekin er åben, når jeg tjekker en frivillig ind manuelt, så kan jeg markere en frivillig på vagtplanen som hhv. fremmødt, afbud og udeblevet.

@mikkelsl er du enig? Skal denne genåbnes eller skal jeg oprette en ny task?

**Comment by mikkelsl** [comment]
Helt enig, har lavet #158 i Todo med det samme
