### ISSUE TITLE
Omdøbe "My side" til "My page"

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#120]

**Comment by MartinQwist** [comment]
Min side hedder "My page" - og ikke "My side" - på engelsk. 

![Image](https://github.com/xooom-community/product/assets/167326849/ee44dbbf-ff73-45ea-baa6-4b79f58a998c)

**Comment by mikkelsl** [comment]
Vi kommer nok til at lave det om på længere sigt, men har bare gjort det.
