### ISSUE TITLE
Ændringsforslag til arrangører

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#121]
# Løser 38.2 i acceptkriterier

Givet at jeg som admin vurderer revisionsforslaget, kan jeg anmode om yderligere ændringer før endelig godkendelse.

**Comment by MartinQwist** [comment]
Kan nedprioriteres til fordel for Priority 1 i Volunteering.

**Comment by MartinQwist** [comment]
Fin løsning, der afspejler den løsning, vi talte om. 

Jeg har et par kommentarer:
- Pop uppen skal også fungere på dansk: 

![Image](https://github.com/xooom-community/product/assets/167326849/b502da01-94c6-41ce-a429-ab4736e93339)

- Der mangler jf. kriterie 38.1, at man kan se den foreslåede redigering. Lige nu kan man kun se hele eventet, der sendes til genudgivelse. Vi foreslog oprindeligt en form for markerede ændringer (a la Track Changes i tekstbehandlingsapps). Men det kunne også laves mere simpelt: F.eks. en Ændringer-boks, der opsummerer, hvilke områder, der er ændret.

**Comment by MartinQwist** [comment]
Som jeg skrev i #52 : Vi foreslog oprindeligt en form for markerede ændringer (a la Track Changes i tekstbehandlingsapps). Men det kunne også laves mere simpelt: F.eks. en Ændringer-boks, der opsummerer, hvilke områder, der er ændret. Men hvis I har et godt greb om det, så ville Track Changes da være at foretrække.

**Comment by MartinQwist** [comment]
Er denne i Preview nu?

**Comment by mikkelsl** [comment]
Det skulle gerne være ude og oversat nu.
