### ISSUE TITLE
Gennemtjek og fiks invitation af næste på venteliste

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#130]
Fra Malene: 

Der er noget galt med ventelisten. Den tager ikke den næste på listen.

Situationen var at jeg i går fik et afbud, som jeg gik ind og slettede, derefter tog den automatisk den første på ventelisten op, hende ringede jeg til og hun afslog vagten via den automatiske mail hun fik. Men nu sender den ikke en mail til den næste der er på ventelisten?

Jeg håber det kan blive rettet forholdsvis hurtigt, da vi går ind i 6 uger, hvor dette vil opstå mange gange.

![image](https://github.com/xooom-community/product/assets/167326849/f31710cd-88f5-484f-bd9c-2fd6f8a099d2)

**Comment by MartinQwist** [comment]
`Havde der været en mere på ventelisten, havde den næste person fået tilbuddet i stedet.`

Det melder Malene, ikke er tilfældet.

**Comment by MartinQwist** [comment]
@mikkelsl og @antonlund18 Hvad siger I til ovenstående forslag med at løse den gennem kollisionsstyring?

**Comment by mikkelsl** [comment]
Anton har sørget for, at man ikke kan tilmelde sig ventelister samtidig med andre ventelister og vagter 👍

**Comment by MartinQwist** [comment]
Smukt! Nu vil jeg snart i seng. Vi ses.
