### ISSUE TITLE
Sortering/filtrering af frivillige

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#131]
# Løser 44.1 i acceptkriterier

Givet at jeg er admin, når jeg fremsøger profiler, så får jeg vist brugerlister, som kan sorteres og filtreres.

# Løser 46.1 i acceptkriterier

Givet at jeg er admin, når jeg fremsøger brugerprofiler (frivillige) på ud fra navn, mail, telefonnummer, fødselsdato, sprog, erfaringsniveau, aktivitetsniveau, aktiv/passiv, oprettelsestidspunkt, gruppemedlemsskaber og eventdeltagelse, så returneres en liste over brugere som kan sorteres og filtreres.

- [x] Sorter på seneste medlem
- [x] Sorter på seneste login

**Comment by MartinQwist** [comment]
Kan nedprioriteres til fordel for Priority 1 i Volunteering.
