### ISSUE TITLE
Udvidelse af mailskabeloner/automail

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#151]
# Løser 5.1 i acceptkriterier

Når jeg til-/fravælger en kanal til en række notifikationstyper, så vil jeg fremover modtage notifikationer for hver type gennem de valgte kanaler.

# Løser 51.1 i acceptkriterier

Givet at jeg er admin, så har jeg adgang til en oversigt over alle notifikationstekster. 

# Løsning

### Se "Notifikationer" under Excel ark med acceptkriterier for detaljer

- [x] Systemmail: Inaktivitet, advisering
- [x] Systemmail: Deaktivering, advisering
- [x] Systemmail: Deaktivering
- [x] Mailskabelon: Godkendelsesemail til arrangør
- [x] Mailskabelon: Afslagsemail til arrangør
- [x] Mailskabelon: Frivillig har oprettet sig
- [x] Systemmail: Frivillig er logget ind
- [x] Systemmail: Frivillige er tilmeldt en vagt

## Vi skal have gennemgået, om de her skal laves

- Bruger er oprettet
- Event oprettet, tilmelding åben, framelding åben
- Event oprettet, tilmelding åben
- 3 dage efter vagtdag slut

**Comment by MartinQwist** [comment]
Se her: https://docs.google.com/spreadsheets/d/1SdoDh-XaMnArgCeEN56YkYrTzz0eYTH0jtwczWgqs9Q/edit#gid=0

Bemærk sammenhæng  til Volunteering #198

**Comment by MartinQwist** [comment]
Note: Handler jf. 5.1 også om forskellige muligheder for notificering. Som udgangspunkt kan brugere notificeres via mail og platform. Default varierer.

**Comment by MartinQwist** [comment]
Jeg har opdateret udkast til automails og notifikationer her: https://docs.google.com/spreadsheets/d/1xocGICUCHaEGjVw1L8CM6EqDJ-HtJnThWa0K1uIHVzk/edit?gid=1947125782#gid=1947125782. Se fanen Notifikationer. Det er godkendt af Rethinker.

**Comment by mikkelsl** [comment]
![Image](https://github.com/user-attachments/assets/e658629e-b2a7-4202-8e5a-97e867a76840)

**Comment by mikkelsl** [comment]
- Der eksisterer en "deleteUser" under user-mutation.service.tsx, som bare kan bruges direkte ved endelig sletning af bruger
- Vi snakkede om, at der skal laves en grace period, hvor man har mulighed for at fortryde

**Comment by antonlund18** [comment]
Mailskabeloner med godkendelse og afslag til arrangører løst i: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=76946617

**Comment by antonlund18** [comment]
Systemmails vedr. inaktive brugere løst i: #307
