### ISSUE TITLE
Acceptkriterier

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#152]
Jeg har markeret alle de acceptkriterier, der står som ikke accepteret, men hvor jeg ikke er afklaret omkring, hvordan de skal løses med "AFVENTER MARTIN" i lilla. Det ville give mening at tage fat i nogle af dem på næste møde.

Derudover må du gerne se, om du er enig i, at alle acceptkriterier, hvor der står "Løst her", lever op til kravene.

Bare flyt den her til "Accepted", når du har læst det.

**Comment by MartinQwist** [comment]
Så har jeg løst igennem og kommenteret. Jeg går i gang med dem, som fortsat afventer mig.
