### ISSUE TITLE
Tilmelding til vagter efter tilmeldingsfrist

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#155]
Rethinker Aarhus efterspørger mulighed for at frivillige kan tilmelde sig vagter efter tilmeldingsfristen.

Fx et scenarie hvor en frivillig melder afbud efter tilmeldingsfristen, og der ikke er nogen på ventelisten. Lige nu tilføjer Rethinker Aarhus de frivillige som administratorer på arrangøren for at kunne melde dem på vagten.

Arrangørene burde ikke have mulighed for at påtvinge vagter på frivillige. Et løsningsforslag kunne være at stadig gøre det muligt at tilmelde sig ventelisten efter tilmeldingsfristen.

**Comment by mikkelsl** [comment]
Man kan bare forlænge tilmeldingsfristen

**Comment by mikkelsl** [comment]
Opsplitning af tilmeldingsfrist og afmeldingsfrist er allerede her: https://github.com/orgs/xooom-community/projects/2?pane=issue&itemId=62245032
