### ISSUE TITLE
Slet af grupper, der ikke har vagter eller frivillige

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#162]

**Comment by mikkelsl** [comment]
Hænger den sammen med den her: https://github.com/xooom-community/product/issues/159

**Comment by mikkelsl** [comment]
Den der har oprettet en gruppe, bliver automatisk sat som "medlem" af gruppen, så logikken skal nok være, at hvis der kun er 1 medlem og ingen vagter (allocations), så kan man slette gruppen (mangler der evt. cascade på relationer)

**Comment by henrikbak** [comment]
@antonlund18 Der var været en tilbagemelding på at man får at vide at man ikke kan slette en gruppe, fordi der er vagter på, men der er ikke nogen vagter at se i interfacet.

Jeg tænker at tjekket for om der er vagter i gruppen eller ej skal droppes, så man kun blokerer for at slette gruppen, hvis der er medlemmer.
