### ISSUE TITLE
Mulighed for selv tjek in skal slettes eller ændres

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#164]
# Løser 17.1 i acceptkriterier

Lige nu kan frivillige tjekke sig selv ind når som helst. Også, hvis de ikke er fremmødt. Det skal de ikke kunne, da fremmøde til tilmeldte vagter er en kerneværdi for alle frivilligorganisationer. 

Den er muligvis indført sfa. en bogstavelig læsning af delkriterie 17.1. Den overordnede user story lyder: Som frivillig vil jeg gerne kunne registrere mit fremmøde, når jeg møder op til en tilmeldt vagt, så jeg 1)kan undgå udeblivelse, så 2)arrangøren ved, at jeg er ankommet og så 3)så vagten fremover fremgår af min historik.

Vi kan kigge på muligheden for selvtjekin, når det bliver muligt at bruge funktioner på den frivilliges eget device (location, kamerascanning eller andet).

**Comment by mikkelsl** [comment]
Der er en begræsning på, at man kun tjekke sig ind 60 min. før og efter start af eventet er startet lige nu.
Det er korrekt, at der ikke et geografisk tjek, QR eller lignende.

**Comment by MartinQwist** [comment]
Tjek. Men det skal stadig ikke være muligt for en frivillig at tjekke sig selv ind med mindre det er knyttet op på en fysisk eller digital verifikation af location.

**Comment by mikkelsl** [comment]
Tjek ind knap for frivillige er fjernet efter aftale.
Knappen kan genindføres senere ifm. mobil app, hvor lokation kan tjekkes.

**Comment by MartinQwist** [comment]
Knappen er enten ikke fjernet eller genindført. I onsdags kunne frivillige til vores fyraftensmøde sidde under mødet og tjekke sig selv ind via mobiltelefon :-).

**Comment by henrikbak** [comment]
@MartinQwist Jeg har lige testet og kan ikke se at man som frivillig kan tjekke sig selv ind. Når man er markeret som holdleder, kan man til gengæld tjekke sig selv og frivillige på samme hold ind. Kan det have været tilfældet her?

**Comment by MartinQwist** [comment]
Hmmm. Det kan jeg godt se. Sært. Jeg prøver lige at se, om jeg kan genskabe det.

**Comment by henrikbak** [comment]
Jeg har fjernet "Tjek ind klar" som står ude i sidebaren lige inden og under vagten.
