### ISSUE TITLE
Bottom navigation forsvundet på mobil

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#165]
Det ser ud til at bottom navigation kun kommer frem, når man scroller ned på mobil.

Det kan sandsynligvis være en side effect af løsningen til den her: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=60082156

På iOS (Christina) kan man slet ikke finde bottom navigation på f.eks. den her portal: https://xooom.dk/portal/byens-hus

**Comment by MartinQwist** [comment]
Jeg har ikke oplevet denne fejl, og jeg kan heller ikke genskabe den. Så OK herfra.
