### ISSUE TITLE
Tilføj tlf nr til vagtoversigt

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#167]
Arrangørens side Vagter skal inkludere telefonnummer på den frivillige. Evt. samme sted som email. (E-mail skal på sigt helt væk, når de øvrige kommunikationskanaler spiller bedre).

**Comment by mikkelsl** [comment]
Jeg har tilføjet at telefonnummer skal indgå her: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=66191938

Så jeg lukker denne til fordel for den opgave.
