### ISSUE TITLE
Ændring af opgave til anden opgave

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#17]
- https://rehelper.dk/portal/nyborg-volunteers/event/danehof-en-middelalderfestival-i-verdensklasse-orvk
- https://rehelper.dk/portal/nyborg-volunteers/event/klokkehoj-open-air-2obx
- https://rehelper.dk/dashboard/copenhagen-invitational/events/copenhagen-invitational-2024-gjbc

**Comment by mikkelsl** [comment]
Tidligere rykkede du tasks over i "Accepted", nu kan du bare trykke "Close issue"/"Close with comment" her nederst

**Comment by MartinQwist** [comment]
Denne er accepteret som den er formuleret. 

Men det er en alt for powerfull feature. Særligt nu, hvor de frivillige står som tilmeldt uanset, at man ændrer deres opgave. De burde få status af "Ubekræftet". En status de beholder, indtil eventet er slut. En ubekræftet optager en plads.

**Comment by MartinQwist** [comment]
OK. Jeg foreslår, at du bruger featuren nu til at rette op på arrangementerne i Nyborg, og at featuren derefter deaktiveres. Det kunne være en fin løsning, hvis der kan implementeres en ny ubekræftet-logik i en anden sammenhæng, og vi så kan åbne igen.

**Comment by mikkelsl** [comment]
Er der kommet styr på det med Copenhagen Invitational?

**Comment by MartinQwist** [comment]
Ja, det mener jeg. Jeg synes, at deres opgaveformuleringer virker lidt underlige, men den ligger hos dem. Systemunderstøttelsen er som den skal være.

**Comment by mikkelsl** [comment]
Jeg har gjort, hvad jeg kunne her:
https://rehelper.dk/portal/nyborg-volunteers/event/klokkehoj-open-air-2obx

Nu kigger jeg på den her:
https://rehelper.dk/portal/nyborg-volunteers/event/danehof-en-middelalderfestival-i-verdensklasse-orvk

Og så fjerner vi mulighed for skift at opgave igen.

**Comment by mikkelsl** [comment]
Skulle gerne være væk nu.
