### ISSUE TITLE
Ændre dashboard forside

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#172]
Dashboard forside (Overblik) for arrangører - udskift eventoverblikket uge med eventoverblikket liste. 

Ugeoversigten er ikke så relevant, og tager meget plads i overblikket. Kunne passende erstattes med et andet overblik. På kort sigt er eventoverblikket Liste (der linker til arrangørs events) mere relevant og brugbart.

**Comment by mikkelsl** [comment]
Vi tænker, at man skal gå ind under events for at se en liste over events.

Vi har flere planer med ugekalenderen på sigt, så den skal nok blive mere relevant på sigt.

De øvrige dashboard informationer, vi løbende kommer til at sætte ind, kan fremgå over kalenderen, så den skubbes ned.
