### ISSUE TITLE
Arrangøransøgninger: Manuel/automatisk godkendelse ved accept

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#173]
# Løsning

## Jeg vil forslå at man i selve godkendelsen af en arrangør under "Arrangøransøgninger", kan vælge mellem "Manuel godkendelse" eller "Automatisk godkendelse"

---

Tidligere beskrivelse:
“Manuel godkendelse” som default på nyoprettet arrangør. Lige nu er default “Automatisk godkendelse”. 
Både Nyborg, Aarhus og København bruger mig bekendt kun manuel godkendelse til alle deres arrangører. 

![Image](https://github.com/xooom-community/product/assets/167326849/80470337-bed0-4c2e-897b-e1ad96e73793)

**Comment by mikkelsl** [comment]
Nyborg bruger pt. kun automatisk
Aarhus har 1 arrangør sat til manuel, resten automatisk.

**Comment by MartinQwist** [comment]
Gad vide, om det er fordi det er default eller fordi det er det, de ønsker? Vi havde dette oppe på et møde tilbage i januar, hvor vi blev enige om at det ikke bør være default, fordi vi ikke kan garantere, at en aktørs aktivitet hører ind under vores støttekriterier. Nyborg kan slet ikke, fordi de er kommune. Hvis f.eks. Nyborg Museum beslutter sig til at lave et kommercielt event, så skal de faktisk forlange betaling for det. Men måske de har glemt det eller alligevel foretrækker automatisk som default. 

Jeg hører dem lige ad, og vender tilbage.

**Comment by mikkelsl** [comment]
Jeg vil forslå at man i selve godkendelsen af en arrangør, kan vælge mellem om arrangøren skal sættes til "Manuel godkendelse" eller "Automatisk godkendelse"

**Comment by MartinQwist** [comment]
> Jeg vil forslå at man i selve godkendelsen af en arrangør, kan vælge mellem om arrangøren skal sættes til "Manuel godkendelse" eller "Automatisk godkendelse"

God ide
