### ISSUE TITLE
Arrangøroprettelse vises ikke under Mine organisationer

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#18]
Denne fejl dukker op igen. Denne gang fra Historiske Dage: 

Fra Henrik Thorvald Rasmussen fra Historiske Dage:

Jeg kommer til nedenstående side, når jeg vælger «Bliv arrangør”, hvorefter jeg ikke kan komme videre:

https://ac.webbook.dk/proxy.php?proxy=forward_preview&module=system&v=6.2.7&b=DEV&context=attachments&id=12548&size=118689&md5=7093757369c511d09f4867e19a2ff3ef&timestamp=2024-04-15+09%3A06%3A31&force=1

Historiske Dage er ikke på Kulturens Frivilliges arrangørliste:

https://ac.webbook.dk/proxy.php?proxy=forward_preview&module=system&v=6.2.7&b=DEV&context=attachments&id=12549&size=402055&md5=59de34243f36fc5c85f3afc386e01a8b&timestamp=2024-04-15+09%3A07%3A36&force=1

**Comment by mikkelsl** [comment]
Kan den være løst på magisk vist? Jeg kan simpelthen ikke fremprovokere problemet her.
Har forsøgt at ansøge på forskellige måder.

Har lavet en smule om i koden for at se, om vi kunne være heldige at ramme et eller andet.

**Comment by MartinQwist** [comment]
OK, vi ser ad, om der evt. er lagt lidt magi ind i koden :-).

Kan du evt. tage at oprette en ny organisation fra forsiden af Kulturens Frivillige ("Bliv arrangør") med en "frisk" e-mail adresse? Så ser vi om du dukker op hos mig.

**Comment by MartinQwist** [comment]
Jeg kan ikke genskabe problemet. Så jeg tror, den er løst. Ungdommens Folkemøde har sidenhen kunnet oprette sig.
