### ISSUE TITLE
Forbedrede til-/afmeldingsfrister

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#19]
# Løses i bytte for 29.3 og 41.1 i acceptkriterier

~~LØST: Det er lige nu et problem, at man ikke har særligt gode muligheder for at definere tidsskema for tilmelding og framelding. I dette eksempel lukker tilmelding for alle vagtdage hele sommeren 29. marts~~

Man skal for hver vagtdag vælge tre datoer:
- Til-/framelding start (default: dags dato)
- Framelding luk (default: 14 dage før vagtdag. senest mulige tidspunkt: Midnat før vagtdag)
- Tilmelding luk (default og senest: Midnat før vagtdag)

Kodeteknisk regner jeg med, at vi laver en helt separat relation, der ligner "shiftRegistrationWindow" og i stedet hedder "shiftUnregistrationWindow", der bruger samme model til at håndtere afmeldingsvinduet.

---

- [x] shiftUnregistrationWindow i databasen
- [x] UI til at oprette tilmeldings- og afmeldingsvindue på eventdatoer
- [x] Tjek og håndter afmeldingsvindue i portalen (UI/UX)
- [x] Valider om vagt er indenfor afmeldingsvinduet, inden den slettes (shiftUnregister i UserResolver)

**Comment by mikkelsl** [comment]
Lige nu har vi:
- Tilmelding starter
- Tilmelding/framelding slutter

Ønsket er at splitte tilmelding/framelding slutter op i:
- Framelding slutter
- Tilmelding slutter

Med henblik på at tilmelding kan fortsætte efter framelding slutter.

**Comment by MartinQwist** [comment]
Hej @mikkelsl . Jeg vil gerne bede om en status på denne opgave til mødet i morgen.

**Comment by mikkelsl** [comment]
Kodeteknisk regner jeg med, at vi laver en helt separat relation, der ligner "shiftRegistrationWindow" og i stedet hedder "shiftUnregistrationWindow", der bruger samme model til at håndtere afmeldingsvinduet.

**Comment by mikkelsl** [comment]
@MartinQwist Melder du tilbage ift., om vi fjerner 29.3 og 41.1 til fordel for denne?

**Comment by MartinQwist** [comment]
@henrikbak Vi aftalte i dag, at "Afmelding - Start" skal skjules, og i øvrigt følge "Tilmelding - Start". Giver du en melding, når det er gjort?

**Comment by henrikbak** [comment]
@MartinQwist Jeg har rettet til og lagt det op i preview. Vil du tage et kig og evt. teste?

**Comment by MartinQwist** [comment]
Det ser rigtig fint ud. Egentlig fint at bevare de to rammer - en til tilmelding og en til framelding. Det er i hvert fald meget tydeligt, hvad man laver, synes jeg. Jeg kan umiddelbart ændre datoer jf vinduet, så jeg accepterer. 

......Pyha! Good job, boys. Lidt af en milepæl, må jeg sige.

**Comment by henrikbak** [comment]
@MartinQwist Denne er i produktion nu. Sammen med en række af de andre opgaver, vi har lavet den seneste uges tid.
