### ISSUE TITLE
Udvidelse af notifikationer

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#198]
Se beskrivelse af notifikationer her: 

https://docs.google.com/spreadsheets/d/1SdoDh-XaMnArgCeEN56YkYrTzz0eYTH0jtwczWgqs9Q/edit?usp=sharing

**Comment by MartinQwist** [comment]
Tasken vedrør user story 5, 6 og 49 og disses acceptkriterier.

**Comment by mikkelsl** [comment]
Jeg lukker den her, da den umiddelbart omhandler det samme som den her i Development: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=65190186
