### ISSUE TITLE
Kontaktperson ved sen afmelding

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#20]
- [x] Sæt en kontaktperson på et event
- [x] Ved klik på afmelding efter afmeldingsfrist, vis kontaktinfo til kontaktperson på eventet
- [x] Default kontaktperson til den der opretter
- [x] Sikre at kontaktinfo på alm. brugere ikke kan hentes

**Comment by mikkelsl** [comment]
Ude om 5 minutter - findes under "Vagter" fanen på overblikket over alle datoer.

**Comment by MartinQwist** [comment]
Det ser rigtig fint ud. 

Der er et par issues:
- Jeg får engelsk tekst både i backend i feltet, hvor jeg skal vælge kontaktperson ("Add contact person") og på portalen, når jeg vælger "Afmeld" efter fristen: 

![Image](https://github.com/xooom-community/product/assets/167326849/8c8c191e-bee3-4bde-8b95-67105b5c65f3)

- Tekst i pop up tekstboks: Slet "We really need your help." Det samme på dansk. Teksten skal være forholdsvist neutral.
