### ISSUE TITLE
Turborepo issue ved Github action build/deploy

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#202]
https://github.com/billetten/xooom/actions/runs/9384078513/job/25839102867

------
 > [installer 8/9] RUN yarn install:
34.83 $ yarn generate:prisma && yarn generate:nexus && yarn generate:frontend
35.03 $ turbo run generate:prisma --cache-dir=.turbo
35.28  ERROR  run failed: error preparing engine: Could not find the following tasks in project: generate:prisma
35.28 Turbo error: error preparing engine: Could not find the following tasks in project: generate:prisma
35.30 error Command failed with exit code 1.
35.30 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
35.32 error Command failed with exit code 1.
35.32 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
35.35 error Command failed with exit code 1.
35.35 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile.api:32
--------------------
  30 |     COPY --from=build /app/out/full/ ./
  31 |     
  32 | >>> RUN yarn install
  33 |     
  34 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
------

Er ikke helt klar over, hvorfor den pludselig fejler - turborepo har en ny major, ved ikke om der er sket et eller andet, der giver problemer i den forbindelse.

**Comment by henrikbak** [comment]
@mikkelsl Jeg har låst versionen af turbo i docker build-filerne til 1.13.4. Det løser problemet.

Jeg tror problemet var at den installerede version 2 globalt, når den buildede i Docker.

**Comment by mikkelsl** [comment]
Det er smukt! 👍
