### ISSUE TITLE
Kort beskrivelse virker ikke

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#203]
Discussion: https://github.com/orgs/xooom-community/discussions/196

---

Man kan slette men ikke skrive nyt. Her ved Roots&Jazz hos kulturens frivillige i København - som nu er en del af Copenhagen azz Festival:

 ![image](https://github.com/xooom-community/product/assets/167326849/4c4d7a08-a67b-4522-8c81-f03a2628558e)

**Comment by henrikbak** [comment]
@MartinQwist Jeg implementerer det således at man både har mulighed for at skrive "Kort beskrivelse" og "Om", når man laver en arrangøransøgning.

"Kort beskrivelse" bliver begrænset til 80 tegn og det indikeres med XX/80 tegn under feltet. Det gør sig gældende både når laver ansøgningen og under præsentation.
