### ISSUE TITLE
Visning af dropdown menu ifm. notifikation/nyhedsbrev

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#209]
Når Malene og Jens sender reminder ud til de frivillige – bruger de funktionaliteten Nyhedsbreve.

Her står den default til at vælge alle datoer i event…og derfor skal Jens/Malene fjerne alle flueben manuelt undtagen den relevante dato hvor de skal sende reminder.

Men når de skal fjerne alle flueben så ”falder” dropdown menu ned under skærmbilledet…og ja det gør det besværligt at fjerne alle disse flueben.

Kan I lave følgende fix?:

Visning af dropdown menu skal fixes. Den må ikke "falde udenfor skærmen". (bug)
Det skal være default, at den sætter flueben i alle datoer. Lige nu er default ingen flueben. (enhancement)

**Comment by MartinQwist** [comment]
Flueben som default er løst.

At drop down listen ryger ud af skærmen er ikke løst: 

![Image](https://github.com/xooom-community/product/assets/167326849/20dcc5f2-08c6-4c9d-93be-41b90fa1de6f)

![Image](https://github.com/xooom-community/product/assets/167326849/da918f54-c161-4dcf-bf8a-b006cf5a58bd)

**Comment by henrikbak** [comment]
@MartinQwist Preview var vist ikke opdateret. Hvis du tager et kig igen, skulle det gerne være fikset.

**Comment by MartinQwist** [comment]
Så virker det. Den er accepteret.
