### ISSUE TITLE
Mobiloptimering (inkl. notifikationer)

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#21]
## TLDR: Sidebar fra Desktop skal understøttes elegant på mobil

- [x] Favoritter, Aktiviteter og Grupper flyttes ind under fælles tab "Min side", som minder om "Min side" på desktop - måske vi skal have fundet på et bedre navn
- [x] Holdchat, gruppechat notifikationer på mobil
- [x] "Tilmeld dig" knap skal bestå på mobil
- [x] Andre tiltag?

**Comment by MartinQwist** [comment]
Hvordan fungerer ` Holdchat, gruppechat notifikationer på mobil`?

**Comment by mikkelsl** [comment]
Du har fået en tab "Min side" er i bunden med et notifikationstal, hvis du har notifikationer - og når du trykker får du præcis samme liste som "Min side" på desktop, hvor antal beskeder osv. fremgår.
