### ISSUE TITLE
Slå notifikationer og nyhedsbreve sammen

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#211]
Løse tanker til at få den her konsolideret bedre.

Lige nu har vi:

Notifikationer (SMS, email, push)
Nyhedsbreve (email)
Notifikationer er korte beskeder uden formatering, der sendes under Vagter for et event/eventdato

Nyhedsbreve er lange beskeder med formatering, der sendes på sin egen side med segmenteringsmulighed som ovenfor

Vi bør nok slå de to sammen under et central begreb "Beskeder", hvor man kan håndtere begge dele, men hvor vi tydeliggør forskellen - måske vi endda helt skal fjerne muligheden for at sende beskeder under "Vagter" på et event.

**Comment by mikkelsl** [comment]
Eftersom SMS ikke bliver brugt endnu, og vi har slået det fra, indtil der virkelig er brug for det - så har vi slået Nyhedsbreve og Notifikationer sammen under "Beskeder", hvor man lige nu kun kan lave Nyhedsbreve, men senere aktiverer vi igen Notifikationer med SMS osv. På den måde laver vi én samlet hub til alle envejsbeskeder.

**Comment by MartinQwist** [comment]
Det synes jeg er en god og meningsfuld struktur. Jeg gennemgik den med @henrikbak i dag. Jeg synes, at det er et godt og vigtigt skridt, der er taget. Det er stadig work in progress. Vi aftalte i dag, at funktionen er så almen og tidligt i udviklingen, at det mest logiske ville være, hvis I kommer med et bud på, hvad næste skridt er. Så kan vi tage en snak derudfra. Jeg kunne forstå, at I desuden allerede har en række forbedringsideer. Tænker, at bolden ligger hos jer på denne.

**Comment by MartinQwist** [comment]
Kan det passe, at Arkiverede nyhedsbreve er forsvundet? Så vidt jeg husker, så talte vi om en sendt-logik der var, at et nyhedsbrev er i kladde, når det ikke er sendt. Det bliver statisk og kommer i "Arkiv", når det er sendt. Man kan oprette ny besked på baggrund af sendt/arkiveret besked. Dette synes jeg vil være en god løsning.
