### ISSUE TITLE
Holdchat side med visning af alle seneste chatbeskeder

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#213]
- [x] Count på dashboardet med antal uhåndterede conversations
- [x] Ved ny message sæt Conversation status til UNHANDLED
- [x] Mulighed for at sætte Conversation status til HANDLED i adminpanel

**Comment by MartinQwist** [comment]
Er den i preview? Jeg synes ikke, jeg kan finde noget...

**Comment by MartinQwist** [comment]
Så har jeg fundet den. Jeg klikkede på dashboardet. Det mest afgørende er, at man som arrangør kan se, at der er kommet nye beskeder, og det er helt tydeligt nu. Fin løsning.

Jeg savner, at have en samlet adgang til alle mine chats til aktuelle events med markering af, hvornår seneste besked blev skrevet der. Når man klikker marker som læst, så forsvinder de fra overblikket. Enten kunne jeg tænke mig et integreret overblik af læste og ulæste - evt. sorteret med læste nederst. Eller jeg kunne tænke mig en fane med hhv. læste og ulæste. 

Kan jeg oprette et nyt ønske om det i Volunteering? Eller tænker I, at der er noget på vej allerede i den retning? 


Gruppechat. Vi talte på mødet om, at oversigten også inkluderede gruppechats. Men det gør det ikke pt. så vidt jeg kan se. Hvad tænker I her? Der er lidt samme issue med, at man som arrangør har vanskeligt ved at følge ned i nye indlæg. Jeg kan evt. oprette ønske på det i Volunteering.

**Comment by henrikbak** [comment]
@MartinQwist Jeg får lavet det som en side, som også kan fremgå af menuen, så den bliver lidt lettere at finde ind til. Jeg tænker det er en fin idé at oversigten kan komme til at indeholde alle holdchats på sigt - uanset om de er læste eller ej. Du må gerne oprette et ønske på dette i volunteering.

Angående gruppechats så var vores tanke at man ser nye beskeder via "Min side" på portalen, da man som arrangør typisk er medlem af grupperne.

**Comment by henrikbak** [comment]
@MartinQwist Nu har jeg gjort det muligt at lægge siden i brugermenuen til venstre. Det ligger klar i preview.

**Comment by MartinQwist** [comment]
@henrikbak Det lyder godt. Hvad hedder siden?

**Comment by henrikbak** [comment]
Her eksempelvis: https://preview.rehelper.dk/dashboard/rethinker-aarhus/conversations

Det er også den side du rammer, når du klikker på boksen "Aktive holdchats" på dashboardet. Forskellen fra før er bare at du kan stjernemarkere den, så den ligger i menuen til venstre.

**Comment by MartinQwist** [comment]
Ah, nu kan jeg se den. Tak. Lille med god forbedring.
