### ISSUE TITLE
Mulig fejl i kundegrupper

### ISSUE THREAD

**Issue by ChristinaZT** [xooom-community/product#217]
Kunder, der ikke kan sende forespørgsler til noget som helst. Heller ikke til lokaler, hvor det har adgang til:

- Globale Seniorer har fx prøvet at sende en forespørgsel til Store Claus, og når de trykker på Send forespørgsel, sker der ingen ting.
- Backgammonklub har prøvet at sende en forespørgsel til Forsamlingen og får en besked – You dont have an access to this room
- A3A har prøvet at sende en forespørgsel til Lille Claus og får en besked – You dont have an access to this room
- Frivilligcenter Gentofte har prøvet at sende en forespørgsel til Forsamlingen og får en besked – You dont have an access to this room
- Udover dette problem, har vi en arrangør, der er en kontaktperson/hovedansvarlig til to organisationer – Røde Kors Gentofte og Blixen Klub Onsdag. Hun har en mailadresse tilknyttet til en forening, og en anden mailadresse til en anden forening.
Hun kan komme ind, når hun trykker på linket fra mailen – Gå til portalen, men der er ikke en forbindelse til foreninger. Dvs. at hun ser ingen ting under Min side og under Mine organisationer.

**Comment by ChristinaZT** [comment]
Mail fra kunden. Jeg kan ikke se der er fejl i opsætning i nogle af de nævnte kunder: 

---------

Hej Christina

Kunder, der ikke kan sende forespørgsler til noget som helst. Heller ikke til lokaler, hvor det har adgang til:

Globale Seniorer har fx prøvet at sende en forespørgsel til Store Claus, og når de trykker på Send forespørgsel, sker der ingen ting.

Backgammonklub har prøvet at sende en forespørgsel til Forsamlingen og får en besked – You dont have an access to this room

A3A har prøvet at sende en forespørgsel til Lille Claus og får en besked – You dont have an access to this room

Frivilligcenter Gentofte har prøvet at sende en forespørgsel til Forsamlingen og får en besked – You dont have an access to this room:

 


Udover dette problem, har vi en arrangør, der er en kontaktperson/hovedansvarlig til to organisationer – Røde Kors Gentofte og Blixen Klub Onsdag.
Hun har en mailadresse tilknyttet til en forening, og en anden mailadresse til en anden forening.
Hun kan komme ind, når hun trykker på linket fra mailen – Gå til portalen, men der er ikke en forbindelse til foreninger. Dvs. at hun ser ingen ting under Min side og under Mine organisationer.

Bedste hilsner
Anette

**Comment by henrikbak** [comment]
@ChristinaZT Tror du det første eksempel kan være fra inden, jeg lavede et fiks i sidste uge, hvor jeg sørgede for at fejlbeskeder bliver udskrevet?

De næste tre eksempler er relateret til fejlen "You dont have access to this room". Den fejl kommer hvis man forsøger at booke et lokale, som ikke er i den kundegruppe, som kunden er en del af. Så beskeden må være at de skal tjekke om det lokale de forsøger at booke rent faktisk i den kunnegruppe som kunden er en del af.

Det sidste punkt er lidt sværere at forstå, men min tanke er de at igen ikke har fået sat det ordentligt op. Jeg kan godt genskabe en lignende situation lokalt. De skal tjekke at de har offentliggjort lokalet, og så skal de tjekke om brugeren er i den rigtige kundegruppe, som desuden har adgang til lokalet.

**Comment by ChristinaZT** [comment]
De mener at de ikke får lov til at booke på de lokaler, som der ligger i den kundegruppe, de er tildelt :/

**Comment by henrikbak** [comment]
@ChristinaZT Jeg har lige lavet en stikprøve, og det ser ikke ud til at de har set det rigtigt op. A3A prøver at booke lokalet "Lille Claus", men dette lokale er ikke en del af kundegruppen "Netværk og foreningsliv". Mon ikke de andre eksempler er lige sådan.
