### ISSUE TITLE
Fejl ved frivillige fra venteliste

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#219]
### Discussed in https://github.com/orgs/xooom-community/discussions/216

<div type='discussions-op-text'>

<sup>Originally posted by **MartinQwist** June 12, 2024</sup>
Fra Malene: 

Jeg skulle slå en frivillig (Lisa Hansen) op, for at se hvornår hun havde næste vagt. Da jeg gjorde det undrede det mig at jeg ikke kunne se hendes vagt i dag, selvom hun står på vagtplanen. Hun sagde at hun først har stået på venteliste og sidenhen fået invitationen til vagten.

Så der må været et glip et sted.

Vagten hun er på:
![image](https://github.com/xooom-community/product/assets/167326849/5aa82fe9-f03e-40ac-a6f7-fdea5cbab975)

Når jeg slår hende op:
![image](https://github.com/xooom-community/product/assets/167326849/66cb5a12-8be1-4e74-a22c-cd3789d6d4dd)

Det samme gælder for frivillige/medarbejdere der er tildelt en vagt via backenden. Deres vagter fremgår heller ikke af denne oversigt.</div>

**Comment by MartinQwist** [comment]
Jeg har lidt mere til denne fra Malene: 

Det er meget misvisende at det ser ud til at vagterne er fuld besat, især når invitationen er udløbet. Så skulle systemet meget gerne gå ind og fjerne den frivillige.

![image](https://github.com/xooom-community/product/assets/167326849/fbe41af8-5477-4303-a3b6-9c64067e7502)

**Comment by mikkelsl** [comment]
Det er meget mystisk. De vagter som ikke fremgår på billedet, er under hendes profil nu. Vi filtrerer ikke umiddelbart på vagterne, så det bedste bud er, at det har været et kortvarigt cache problem.

Hvis det sker igen, må I melde det ind igen.

**Comment by mikkelsl** [comment]
Problemet er at den frivillige på en eller anden måde er oprettet hos "Ragnarok", og de vagter der er taget med "Ragnarok" frivilligskabet, kan ikke ses i "Rethinker Aarhus" oversigten (2 forskellige organizerUsers)

**Comment by MartinQwist** [comment]
OK. Den fejl kan jeg godt huske. Kan man flytte alle Ragnarokoprettede frivillige over i Rethinkers frivillige?

**Comment by mikkelsl** [comment]
I starten var der åbent for at arrangører under en frivilligorganisation kunne have deres egen portal. På den måde ville de kunne få deres egne organizerUsers direkte (som Muskelsvindfonden f.eks. også gerne vil have, samtidig med at de kan få hjælp fra Rethinker og Kulturens). Jeg troede egentlig alle "dobbelt" organizerUsers, som både er hos arrangøren og frivilligorganisationen kom af det - men selv efter vi har lukket ned for portalerne, virker det til at der bliver oprettet dobbelt organizerUsers af og til.

Det har ikke nogen betydning for den enkelte frivillig lige nu, men jeg tænker opgaven er todelt:

- Find ud af hvorfor der bliver oprettet en organizerUser hos arrangøren også og luk hullet
- Flyt alle organizerUsers fra arrangører til deres tilsvarende organizerUser hos frivilligorganisationen på samtlige shifts - og fjern alle organizerUsers af typen VOLUNTARY fra arrangørerne (den her skal vi være meget sikre på)

**Comment by antonlund18** [comment]
Det ligner at Lisa Hansen har en bruger, hvor hun er frivillig to forskellige steder: Rethinker-Aarhus (Organisation) og Ragnarok (Arrangør). Normalt bliver man kun oprettet som frivillig ved organisationen, men det ligner at hun er blevet oprettet som administrator (og bagefter lavet om til frivillig) på Ragnarok, så man kunne sætte hende på en vagt fra dashboardet af.

Løsningen blev derfor for nu, at vi også viser vagter fra frivillige fra arrangører, på vagtsiden for frivillige fra organisationen. 

Der er stadig en opgave i, hvordan vi håndterer at arrangører kan force en frivillig på en vagt, uden at de bliver oprettet som frivillige på arrangøren. Jeg aftalte med Ulla, at hun vil snakke med Martin og Marlene, om krav og ønsker og så genbesøger vi den.
