### ISSUE TITLE
Engelsk site viser dansk opgavebeskrivelse

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#22]
Her er jeg på en gruppeside. Opgavebeskrivelserne på den engelske udgave vises på dansk: 

https://ac.webbook.dk/proxy.php?proxy=forward_preview&module=system&v=6.2.7&b=DEV&context=attachments&id=12533&size=1196714&md5=1f03f43e4458d67563a6373661ae7bec&timestamp=2024-04-10+13%3A03%3A15&force=1

**Comment by mikkelsl** [comment]
Problemet her er kendt, og opstår kun når man er logget ind og skifter sprog. Indtil man logger ud og ind ved backenden ikke at sproget er skiftet.
- Vi skal sikre at frontend får et opdateret JWT, hver gang der laves om på session relateret data "ctx.session" i backenden

Ikke en nem opgave, men lad os få det løst.

**Comment by antonlund18** [comment]
Af sikkerhedsmæssige årsager, har vi tilføjet et adgangstjek, for at skifte sprog. Vi er opmærksomme på, at det virker lidt underligt for brugeren, at de skal indtaste deres kodeord for at skifte sprog - det giver dog nogle større tekniske udfordringer, hvis vi gerne vil gøre det på en mere brugervenlig måde, uden at introducere store sikkerhedshuller. Vi har planlagt at give dette endnu et rul senere, og fokusere på at lave nogle fede features til brugerne for nu :-)
