### ISSUE TITLE
Deaktiver forside. Events som ny forside

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#227]
Pt. vises de næstkommende events øverst på portalforsiden. Længere nede vises nogle arrangører. Så vidt jeg kan vurdere, så er vises de sorteret efteroprettelsesdato. 

Dermed er det altid de samme arrangører der vises på forsiden. Dette er ikke hensigtsmæssigt, da det ikke afspejler et relevant behov fra hverken frivilligorg eller frivillige. 

Forside deaktiveres for nu. Brugere lander på events-side.

**Comment by MartinQwist** [comment]
Bemærk sammenhæng til #256 og #257

**Comment by mikkelsl** [comment]
Ønsket er at der kun skal være events på forsiden.

Vi har en enkelt udfordring med at forsiden også kan indeholde lokaler, hvordan håndterer vi det?

Arrangører kan fjernes uden problemer.

**Comment by henrikbak** [comment]
> Ønsket er at der kun skal være events på forsiden.
> 
> Vi har en enkelt udfordring med at forsiden også kan indeholde lokaler, hvordan håndterer vi det?
> 
> Arrangører kan fjernes uden problemer.

Jeg tænker følgende logik:

- Hvis man udelukkende har events vises alle events på forsiden
- Hvis man udelukkende har lokaler vises alle lokaler på forsiden
- Hvis man har både events og lokaler vises et udpluk af begge på forsiden

Arrangører udgår helt fra forsiden uanset hvad, men eksisterer stadig på undersiden "Arrangører".
