### ISSUE TITLE
Dashboard elementer

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#231]
# Løser 54.1 i acceptkriterier

Givet at jeg er admin, så har jeg adgang til et dashboard, som viser de mest centrale aktivitets- og brugerdata og udviklingen i dem i forskellige grafiske opsætninger – f.eks. pie charts, søjlediagrammer, tabeller, kurver, heat maps etc.

# Løser 54.2 i acceptkriterier

Givet at jeg er arrangør, så har jeg adgang til et lignende dashboard, men som er målrettet mig som omhandler mine aktiviteter.

# Løser 54.3 i acceptkriterier

Accept af begge acceptkriterier forudsætter, at de to dashboards – eller de to visninger – hver indeholder min. 5 elementer, som er målrettet hhv. admin og arrangører, og at der redegøres for, hvordan det kan udvides på et senere tidspunkt.

---

# Dashboard for aktiviteter skulle gerne være løst ved nedenstående

## Frivilligorganisation skulle gerne have mindst 9 relevante elementer (kræver brug af "Foreslået menu"):
- Antal frivilligansøgninger
- Antal chats
- Antal eventansøgninger
- Antal arrangøransøgninger
- Antal kommende eventdatoer
- Antal kommende vagter
- Antal administratorer
- Antal frivillige
- Antal arrangører

## Arrangører skulle gerne have mindst 5 relevante elementer (kræver brug af "Foreslået menu"):
- Antal gruppe ansøgninger
- Antal chats
- Antal kommende eventdatoer
- Antal kommende vagter
- Antal administratorer

# Dashboard for statistik skulle gerne være løst ved nedenstående

- [x] Antal frivilligtimer taget
- [x] Antal frivilligtimer udbudt
- [x] Vagter taget
- [x] Vagter udbudt
- [x] Antal brugere, der har været logget ind (antal portalaktive frivillige)
- [x] Antal brugere, der har færdiggjort en vagt (antal frivilligaktive frivillige = fremmødt/godkendt fravær

## Udvidelse af dashboard på et senere tidspunkt
- Her er de øvrige idéer til, hvordan vi kan videreudvikle dashboardet: https://github.com/orgs/xooom-community/projects/2/views/2?pane=issue&itemId=69140701

**Comment by MartinQwist** [comment]
Jeg synes, at vi bør lave denne som en af de sidste.

**Comment by mikkelsl** [comment]
Er der nogle af de her elementer, der kunne være relevante for jer? F.eks. nye vagter, nye events, nye brugere

![Image](https://github.com/xooom-community/product/assets/11291103/213c1e7a-3218-4947-a790-b56fa6e1611d)

**Comment by MartinQwist** [comment]
Ja, helt klart. Jeg talte med Henrik om at vente med denne som noget af det sidste vi laver. Men hvis I har noget allerede, som er let at implementere, så kan vi også implementere det nu, og så bruge det et stykke tid før vi så senere videreudvikler. Er det tanken? 

I så fald, og ud fra ovenstående, vil jeg vurdere følgende som interessant: Antal brugere, antal nye brugere, antal overståede evnets og eventdage, antal kommende events og eventdage, vager udbudt - vagter taget (to kurver i samme diagram, der viser noget om udbud og efterspørgsel), aktive brugere (måske to typer: 1) Antal brugere, der har været logget ind, 2)Antal brugere, der har færdiggjort en vagt). 

Fra Kulturens Frivillige-perspektiv kan jeg sige: Vores mest centrale KPIer er (med **fed**) **antal portal-aktive frivillige** (dvs. frivillige, der har logget sig ind i platformen) og **antal frivillig-aktive frivillige** (dvs. antal færdige vagter med en fremmødt frivillig eller med godkendt fravær). Her kan man måske vælge periode - i dag, i går, seneste uge, måned, 3 mdr, 6, mdr, 12 mdr osv. Derudover antal vagter og **frivilligtimer**. Både overståede og det antal vagter og frivilligtimer, der er udbudt på portalen til kommende events. 

Derudover vil det være godt med data om, hvordan de enkelte events performer: Hvornår melder de frivillige sig til? Og hvornår melder de sig fra? Hvilke opgaver fyldes hurtigst op? o.l. Desuden frivilligprofil på eventniveau: Hvor gamle er de frivillige? Hvor erfarne er de (antal frivilligtimer)? Hvor kommer de frivillige fra? Hvor mange frivillige er danske og hvor mange er internationale? 

Vi vil også gerne kunne følge de frivilliges aktivitet for at kunne monitorere, hvordan vi fastholder og skaber mere frivillighed: Hvor mange frivillige har taget hhv. 1, 2, 3 osv. vagter indenfor en given periode?

Jeg synes desuden, at det kunne løse en del af behovet, hvis I laver et JSON-feed eller lignende, hvor f.eks. Kulturens Frivillige og Rethinker kunne opbygge en fremstilling i PowerBI eller lignende. 

Håber, det hjælper.

**Comment by mikkelsl** [comment]
Det er super, vi kan lige så godt få beskrevet ønsker og behov. Vi har en del komponenter og funktioner allerede, så hvad der virker som en stor opgave, kan godt være relativt overkommelig.

**Comment by mikkelsl** [comment]
Skulle gerne være løst ved nedenstående

### Frivilligorganisation skulle gerne have mindst 9 relevante elementer (kræver brug af "Foreslået menu"):
- Antal frivilligansøgninger
- Antal chats
- Antal eventansøgninger
- Antal arrangøransøgninger
- Antal kommende eventdatoer
- Antal kommende vagter
- Antal administratorer
- Antal frivillige
- Antal arrangører

### Arrangører skulle gerne have mindst 5 relevante elementer (kræver brug af "Foreslået menu"):
- Antal gruppe ansøgninger
- Antal chats
- Antal kommende eventdatoer
- Antal kommende vagter
- Antal administratorer

### Udvidelse af dashboard på et senere tidspunkt
- Her er de øvrige idéer til, hvordan vi kan videreudvikle dashboardet: https://github.com/orgs/xooom-community/projects/2/views/2?pane=issue&itemId=69140701

**Comment by mikkelsl** [comment]
Det skulle gerne være ude og oversat nu.
