### ISSUE TITLE
Sortering/filtrering af arrangører

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#232]
# Løser 47.1 i acceptkriterier

Givet at jeg er admin, når jeg fremsøger brugerprofiler (arrangører) på ud fra navn, mail, telefonnummer, fødselsdato, arrangørorganisation, oprettelsestidspunkt, stilling/funktion, tidligere-, aktuelle- og kommende events (arrangører tilknyttet hertil), så returneres en liste over brugere som kan sorteres og filtreres.

# Løser 48.1 i acceptkriterier

Givet at jeg er admin, når jeg fremsøger brugerprofiler på titel, mail, oprettelsesdato, tilknyttede arrangører, telefonnummer, cvr, events, så returneres en liste over arrangørorganisationer, som kan sorteres og filtreres.

---

- [x] Vis antal tidligere events
- [x] Vis antal kommende events

Ekstra stamdata for ansøgende organisationer er løst her: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=69114281

**Comment by MartinQwist** [comment]
Jeg kan se i preview, at oplysningerne om tidligere og kommende events er tilføjet. Men ikke at man kan sortere. Har jeg overset noget?
