### ISSUE TITLE
Tilføj Vagter til foreslået menu

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#234]
Arrangørerne i Kulturens Frivillige er glade for siden Vagter. Men kun få lurer, hvordan de selv tilføjer den til deres sidemenu. Jeg vil tro, at det også må gøre sig gældende i Aarhus. 

Derfor bør siden Vagter tilføjes til "Foreslået menu" for alle arrangører.

**Comment by mikkelsl** [comment]
Godt du siger det 👍
