### ISSUE TITLE
Sortering/filtrering på portal

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#235]
# Løser 1.2 i acceptkriterier

Givet at jeg er på forsiden, når jeg vælger at filtrere og/eller sortere, så kan jeg se forskellige arrangementsoversigter.

- [x] Filtrer på fra dato - løst her: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=62112142
- [x] Filtrer på titel (søgning)

**Comment by MartinQwist** [comment]
Note: Sortering af forside/eventside.

**Comment by mikkelsl** [comment]
Flyttet hertil: https://github.com/orgs/xooom-community/projects/1/views/1?pane=issue&itemId=68791504
