### ISSUE TITLE
Visningsfejl på iOS: Øverste header forsvinder

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#24]

**Comment by mikkelsl** [comment]
Jeg er usikker på, om løsningen her virker. Det er lidt i blinde.
Lad mig vide, hvis det ikke virker.

**Comment by MartinQwist** [comment]
Denne er ikke løst. Jeg har flyttet den tilbage i Todo.

**Comment by MartinQwist** [comment]
![image](https://github.com/xooom-community/product/assets/167326849/5342a9ef-64f3-48b6-bec6-c45893e1bae2)

**Comment by antonlund18** [comment]
@MartinQwist Jeg har prøvet at give dette et forsøg igen - men igen lidt et forsøg i blinde. Vil du prøve at tjekke, om det er blevet løst?
