### ISSUE TITLE
Fjern frivillig ved udløbet invitation

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#243]
Malene:

Det er meget misvisende at det ser ud til at vagterne er fuld besat, især når invitationen er udløbet. Så skulle systemet meget gerne gå ind og fjerne den frivillige.

![image](https://github.com/xooom-community/product/assets/167326849/fbe41af8-5477-4303-a3b6-9c64067e7502)

**Comment by antonlund18** [comment]
Det ligner egentligt at udløbne vagter bliver slettet korrekt, når den går videre til næste på ventelisten. Ventelisten går dog i stå, når datoen for vagten er før dags dato (hvilket jo også giver mening, så de frivillige ikke får tilbud om ugyldige vagter - det kan måske også forklare denne: https://github.com/xooom-community/product/issues/130).

Det virker til at det egentlige problem er at antal tilmeldte giver et forkert overblik, så jeg har ændret det til at den ikke tæller vagter med, medmindre den frivillige har accepteret vagten. Og så har jeg tilføjet en uddybende tekst, om at ventelisten ikke går videre, når vagten er i fortiden.

Det har jo så den sideeffekt at afventende invitationer (der ikke er udløbne) heller ikke bliver talt med. Hvis det ønskes at de gør det, kan vi gøre sådan at udløbne invitationer bliver fjernet hver dag.
