### ISSUE TITLE
Problem med magic link på Safari

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#250]
Martin via Discussions: https://github.com/orgs/xooom-community/discussions/228

Når logger ind fra portalen, og trykker mail eller adgangskode forkert, så godtager den ikke den rigtige mail/adgangskode. Man skal først refreshe browseren, før en ny mail/adgangskode godtages.

Vi kan genskabe problemet på Safari på Mac. De fleste af vores arrangører bruger mac.

---

## Undersøg om der er en bug.

**Comment by antonlund18** [comment]
@MartinQwist Er det her stadig et problem for jer? Vi har prøvet at teste det på Safari på en Mac og en anden WebKit baseret browser på Windows, og vi kunne stadig ikke genskabe det.
