### ISSUE TITLE
Invitation og consent per billetdeltager

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#252]
Det skal være muligt at angive navn og email på billetterne, når man køber flere billetter. Det er allerede muligt at angive navn. For at overholde reglerne for GDPR, skal vi indsamle consent fra deltagerne om at vi gerne må gemme deres oplysninger. Dette kan ske ved at man sender en mail ud til deltagerne efter man har indtastet oplysningerne. Deltageren skal derefter godkende ved at klikke på et link i mailen.

Senere kan consents udvides med mere funktionalitet, men dette er hvad der minimum skal til for at løse opgaven.

**Comment by mikkelsl** [comment]
Inviter person som deltager på en billet løses her og lukkes (https://github.com/orgs/xooom-community/projects/3/views/1?pane=issue&itemId=60865803)
