### ISSUE TITLE
Godkende forslag til redigering af publiceret event

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#254]
# Løser 43 i acceptkriterier

![Image](https://github.com/xooom-community/product/assets/167326849/588c4872-8997-4b6f-8934-5428a04429e3)

![Image](https://github.com/xooom-community/product/assets/11291103/1dbce1cc-86b7-4734-a17e-a0635be8a100)

**Comment by henrikbak** [comment]
@MartinQwist Den her ligger klar til test i preview

**Comment by MartinQwist** [comment]
Det ligner en både enkel og brugbar løsning. Indfør gerne navngivning på dansk/engelsk før produktion.
