### ISSUE TITLE
Vis hvilke grupper den frivillige er medlem af under frivilligprofilen i dashboardet

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#268]
Vis ligesom vagter. Der skal være en count i toppen af siden og en liste af grupper.

Dette er et ønske fra Outdoor Festival.

**Comment by MartinQwist** [comment]
Jeg blander mig lige med, hvad jeg tror er et godt råd: Husk altid at gruppers navne altid skal fremgå i kontekst af en arrangør. Alene gruppenavne giver oftest ikke mening, hvis man ikke samtidig kan se, hvem arrangøren er.

**Comment by mikkelsl** [comment]
Har løst det fra den individuelle arrangørs perspektiv, da det primært er brugbart for dem, når de bruger grupper på den måde.

For frivilligorganisationer er det nok mest af alt en nice to know.

Hvis der skal laves mere, kan vi oprette endnu en opgave under ønsker.
