### ISSUE TITLE
Muligt problem med visning af opgaver

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#269]
Se beskrivelse her: https://github.com/orgs/xooom-community/discussions/255

**Comment by antonlund18** [comment]
Det ligner de har oprettet en opgave, tilføjet den til en vagt, arkiveret opgaven, lavet en ny opgave og tilføjet den nye opgave til vagten (osv.):
![Image](https://github.com/user-attachments/assets/c19a3da0-a20b-407c-87e3-64f160babd1e)

Jeg ved ikke helt hvad løsningen skulle være på det - måske implementere at man kan se og gendanne arkiverede opgaver? Jeg tænker det hører til en anden story/issue, så hvis det er okay med dig @MartinQwist, så lukker jeg denne.
