### ISSUE TITLE
Ved afvisning af en forespørgsel – sende kunden en mail

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#286]

**Comment by henrikbak** [comment]
@ChristinaZT Afviser de en forespørgsel ved at slette bookigen i dag? 

Ift. mailen skal det så være en standardformulering eller skal de kunne skrive en specifik tekst hver gang de afviser?

**Comment by ChristinaZT** [comment]
@henrikbak Ja. JEg tænker jo begge dele er at foretrække :)
