### ISSUE TITLE
Når der sendes en bekræftelse på en booking, skal der kunne tilføjes en CC modtager

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#287]

**Comment by henrikbak** [comment]
@ChristinaZT Hvordan foregår bekræftelse af bookingforespørgsler i dag? Er det blot ved at skifte status på en booking fra forespørgsel til booking her eller er der et andet godkendelsesflow jeg ikke kan se?

![Image](https://github.com/user-attachments/assets/be0b3740-a189-4be8-8d76-719eda9fc92e)

**Comment by ChristinaZT** [comment]
Man kan åbne bookingen og gå under handliner og sende en mail. Men umiddelbart er det en lang vej at skal gå :) 
![image](https://github.com/user-attachments/assets/1b6f8646-db5f-416a-9f3d-9aacb764b5cc)
