### ISSUE TITLE
Muligt at sætte et tidspunkt hvorfra man ikke kan sende bookingforesspørgsler efter

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#291]
Der skal naturligvis være en fejlmeddelelse på det. F.eks. der er lukket for bookingforespørgelser efter d. 1/8 2025. Vi skal nok lige tænke over brugeroplevelsen ved seriebookinger.

**Comment by mikkelsl** [comment]
Der var en hel del krav og inspiration omkring den her funktionalitet ifm. Book byen udbuddet, som nok er meget relevant at tænke med i den her.

Der er lavet nogle mockups, som ikke er 100% gennemtænkt, men dog kan give lidt ekstra inspiration til, hvad behovet bliver i et lidt større perspektiv.

Kig f.eks. efter noget med ansøgningsperioder i "bookbyen" under labs folderen, som er et mockup af en booking portal til Book byen.

Derudover ligger der en "kk" folder under dashboard, der bl.a. indeholder "application-periods" m.m.

**Comment by henrikbak** [comment]
@ChristinaZT Vi mangler lidt yderligere afklaring til denne opgave, da den kan forståes på 2 måder.

1. Handler opgaven om at kunne sætte en deadline (dato og tid), hvorefter vi lukker for muligheden for at forespørge om at booke. Altså en simpel funktion som bare lukker for formularen efter en given dato.
2. Handler opgaven om at definere en bookingperiode, hvor man siger at bookeren kun kan forespørge om at oprette bookinger som ligger indenfor en given periode. Eksempelvis kunne bookingperioden være 1. august 2024 til 1. august 2025. Her handler det om hvornår bookingerne må ligge og ikke om hvornår formularen er åben eller ej.

Håber det giver mening for dig, ellers kan vi lige snakke om det.

**Comment by ChristinaZT** [comment]
@henrikbak - Kunden forespørger nummer 2. som du beskriver. 

Sommer og jeg talte kort om, at den nok skulle tænkes mere generel end bare denne kundes behov. Så længe de kan lave en opsætning hvor deres kunder ikke kan lave bookingforespørgsler efter en given dato. Så er de glade. Men vi vil naturligvis gerne gøre alle glade.

**Comment by antonlund18** [comment]
@ChristinaZT Har du en idé om hvor meget kontrol kunderne ønsker? Vil de fx gerne kunne indstille det per lokale, per lokalitet eller på organisationsniveauet? Det kunne også være noget man definerede på lokalegrupper. Jeg tænker det mest intuitive er på lokaler, men det bliver måske lidt træls, hvis man har mange lokaler man gerne vil indstille.

**Comment by antonlund18** [comment]
Kan tilføjes på en lokalegruppe eller på et lokale. Hvis det tilføjes på et lokale tager det effekt frem for lokalegruppen. 

Har lavet en opgave på at give et bedre overblik over hvilke ansøgningsperioder der er aktive for et lokale: #301
