### ISSUE TITLE
Show bookings i kundeportal

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#292]
https://ac.webbook.dk/projects?modal=Task-35434-154

Fra AC:
"Der skal laves en endpoint konfiguration i xooom, under terminal integrationen.

Er denne sat op skal man have mulighed for at oprette show bookings.

I terminal stilles et API til rådighed der ved brug af xooom API keyen tillader at man kan hente promoters, scener ID'er, addresse ID'er (og deres koblings ID) og gemme et event/show i Terminal.

Dermed skulle terminal eje den show booking der oprettes, som så synkroniseres over i Xooom.

Der vil være et behov for at oprette en XOOOOM elektra bruger for alle klienter der har behov for denne løsningen, således at API kan gør brug af denne bruger til at oprette tingene."

**Comment by mikkelsl** [comment]
Det kommer meget nemt til at blive en rigtig dyr fornøjelse på flere parametre over tid.

Det er værd at overveje, om det kan løses på en anden tilfredsstillende måde.
