### ISSUE TITLE
Undersøg optimal serverstørrelse i Scaleway

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#296]
I forbindelse med redeploy har vi for nylig opgraderet vores serverless container for api serveren fra 2000 cpu til 3000, som vist så ud til at fordoble de månedlige omkostninger. 2000 så ud til at være udgået som valgmulighed.

Vi skal have undersøgt, hvor lav en server kapacitet, vi kan køre vores setup med. Det gælder på tværs af alle apps. Kan vi f.eks. nøjes med 1000 cpu på api server, og hvad er trade offs?

Kom med et kvalificeret forslag til serverkapacitet for:
- [ ] API server
- [ ] Frontend servere (Next.js)

Vi skal have tilstrækkelig performance til den lavest mulige pris. Husk at tage i mente, at der skaleres flere server instances op, hvis en server bliver for presset.

**Comment by mikkelsl** [comment]
Foreløbigt er preview blevet konverteret og et par produktionsservere - skal lige være helt skarp på, hvad de sidste produktionsservere skal sættes til, så vi ikke får for lav performance.



![Image](https://github.com/user-attachments/assets/f254cb42-6117-4c76-990b-60c38c7e08ef)

**Comment by henrikbak** [comment]
Jeg har importeret et feed på preview for Silkeborg Bibliotek, som importerer op mod 200 events med billeder. Selve importen er ikke noget problem, men når man tilgår portalen efterfølgende, bliver websitet utroligt langsomt og til sidst utilgængeligt med en 502 response code og en "Internal server error".

Det virker til at det fordi den skal danne alle billederne på events på én side. Man kan så diskutere om det er fordi siden ikke skal indeholde alle events, men jeg tænker også at det er fordi der er skruet ned for kapaciteten på serveren. Hvis jeg tilgår siden nok gange - efter siden går ned ind imellem - så får den dannet alle billederne til sidst, og så er der ikke noget problem fremadrettet.

Bare lige til info - det er ikke noget kritisk

**Comment by mikkelsl** [comment]
Hele preview og enkelte mindre betydelige apps i produktion er justeret, som giver en god besparelse. Vigtige produktionsapps som API, dashboard og portal kan evt. vurderes senere.
