### ISSUE TITLE
Registrering af udeblivelse

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#302]
Der er kommet et behov for registrere folk som udebliver fra deres vagter. Man kan **ikke** gå ud fra at alle vagter uden et check-in , efter arrangementet er afholdt, er lig med en udeblivelse, da det vil kræve at alle arrangører systematisk får registreret fremmøde til deres arrangementer. Derfor er der brug for at det er en status man aktivt kan sætte på vagten (I stil med godkendt fravær).

Jeg forestiller mig følgende statusser:

**Godkendt fravær**
Deltageren har på forhånd givet besked om at vedkommende ikke deltager

**Udeblevet**
Deltageren er udeblevet fra vagten uden at have givet besked

**Ikke fremmødt**
Der er ikke registreret et check-in på vagten

**Fremmødt**
Der er registreret et check-in på vagten

---

Der er flere muligheder, men man kan evt gøre `approvedAbsence` på shift nullable:

true: godkendt fravær
false: ikke godkendt fravær (udeblevet)
null: ingen fravær

Dette vil kræve at vi laver en migrering af feltet og derefter laver et script som sætter alle vagter med approvedAbsence false til null i stedet.

**Comment by MartinQwist** [comment]
Jeg har en lille tilføjelse, som ift. vores arbejdsflow hænger sammen med denne. Lige nu registrerer vi udeblivelser manuelt via tags. Men man kan ikke fjerne tags igen, hvilket er en mangel. Foretrækker I at tilføje fjernelse af tags til denne opgave, eller skal den have sin egen?

**Comment by henrikbak** [comment]
@MartinQwist Jeg har oprettet opgaven her #308

**Comment by MartinQwist** [comment]
Det ser godt ud. Jeg accepterer den. Så er næste skridt det overblik, der gør, at vi kan følge op på fremmøde og udeblivelser.
