### ISSUE TITLE
Systemmail: Udeblivelse fra vagt

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#305]
Der skal automatisk sendes en mail når en frivillig er udeblevet fra en vagt. Vi har talt om det kan være en opsamling som kører 48 timer efter vagtstart.

Der skal kun sendes en mail hvis vagten er aktivt er markeret med status "udeblevet".

Afhænger af #302

---

Udeblivelser er vagter hvor `shift.approvedAbsence === false`

**Comment by henrikbak** [comment]
@MartinQwist Hvad skal der stå i denne mail til den frivillige?

**Comment by MartinQwist** [comment]
Jeg vender tilbage med tekst efter afklaring med Jannie og Ulla.

**Comment by MartinQwist** [comment]
Vores bud:

Kære [Navn],

(English version below)

Vi skriver til dig, da du er registreret som udeblevet fra følgende frivilligvagt:

Event: [Event]
Opgave: [Opgave]
Sted: [Vagtsted]
Tidspunkt: [Vagttidsrum]

Udeblivelse fra en frivilligvagt er i strid med vores fællesskabsregler, som du kan finde på vores hjemmeside. I henhold til disse regler kan gentagne udeblivelser føre til deaktivering af din profil på vores platform.

Kontroller venligst, at du har mulighed for at møde op til eventuelle fremtidige frivilligvagter. 

Din udeblivelse er noteret af kontaktpersonen for [Event], [Kontaktperson Navn], som du kan kontakte på [Kontaktperson Email]. Hvis du mener, at der er tale om en fejl, eller at din fremmødestatus ikke bør betragtes som en udeblivelse, bedes du venligst kontakte vedkommende. 


Venlig hilsen,
[Frivilligorganisation]


---English version---

Dear [Navn],

(English version below)

We are writing to inform you that you have been registered as absent from the following volunteer shift:

Event: [Event]
Task: [Opgave]
Location: [Vagtsted]
Time: [Vagttidsrum]

Absence from a volunteer shift is in violation of our community guidelines, which you can find on our website. According to these guidelines, repeated absences may result in the deactivation of your profile on our platform.

Please ensure that you are available for any upcoming volunteer shifts.

Your absence has been noted by the contact person for [Event], [Kontaktperson Navn], whom you can reach at [Kontaktperson Email]. If you believe this is a mistake or that your attendance status should not be recorded as an absence, please contact the person directly.

Best regards,
[Frivilligorganisation]

**Comment by MartinQwist** [comment]
Vær lige OBS på, at når denne er i Prewiew og Tested, så skal vi lige aftale tidspunkt for deploy, da vi lige skal kommunikere den ud til frivillige og arrangører.

**Comment by MartinQwist** [comment]
Tak, det ser fint ud. Jeg har ikke testet selve udsendelsen. 

Jeg giver jer besked, når den skal med i jeres næste release. Vi har brug for lige at informere frivillige og arrangører ordentligt først.
