### ISSUE TITLE
Mailskabeloner: Godkend/afvis arrangør

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#306]

**Comment by antonlund18** [comment]
Sender e-mail til hovedansvarlig for arrangør ved godkendelse/afslag af arrangør. Bruger mailskabelon hvis den findes, og ellers sender den en default mail:

- Godkendt:
**Du er blevet accepteret som arrangør**
Din ansøgning som arrangør til [frivilligorganisation] er blevet accepteret.

- Afslag:
**Du er blevet afvist som arrangør**
Din ansøgning som arrangør til [frivilligorganisation] er blevet afvist.

**Comment by MartinQwist** [comment]
Tak, det ser fint ud og det virker. Jeg accepterer den nu, men har lige behov for at gennemgå den overordnede funktion med @Henrik på næste statusmøde.
