### ISSUE TITLE
Automail: Send advisering om deaktivering til inaktive brugere

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#307]
![Image](https://github.com/user-attachments/assets/bd92ddf7-f15c-4005-8518-0083ac8e9386)

**Comment by antonlund18** [comment]
@MartinQwist Skal brugere der aldrig har været logget ind, men er blevet oprettet for mere end 18 måneder siden også få en advarsel? Fx ved brugere der er blevet inviteret

**Comment by antonlund18** [comment]
Jeg har ikke inkluderet dem i første omgang. Men det er nemt at tilføje, hvis det ønskes - så sig endelig til, hvis i gerne vil have det😊

Vi kan ikke vise frivilligorganisationens navn, da en bruger potentielt kan være frivillig ved flere forskellige frivilligorganisationer. Men mailsne ser således ud:

**Advisering om inaktivitet**
![Image](https://github.com/user-attachments/assets/00f85760-c536-4569-a467-9551531e0cfa)

**Advisering om deaktivering**
![Image](https://github.com/user-attachments/assets/f7cf268f-f492-4872-b87f-0cd6321744e1)

**Deaktivering**
![Image](https://github.com/user-attachments/assets/9dca0e44-bc21-4718-a763-92af0c9a6b7f)

**Comment by MartinQwist** [comment]
> [@MartinQwist](https://github.com/MartinQwist) Skal brugere der aldrig har været logget ind, men er blevet oprettet for mere end 18 måneder siden også få en advarsel? Fx ved brugere der er blevet importeret, og manuelt får sat oprettelsesdato

Nej, det skal de ikke. Hvis vi nogensinde importerer brugere igen, så må vi se på det til den tid.
