### ISSUE TITLE
Udvidelse af eksporter

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#316]
Acceptkriterie 54 lægger op til et relativt omfattende dashboard inkl statistikbilleder mv. 

Vi kan sandsynligvis med fordel dele denne op, og anvende dashboard til dag-til-dag styringsdata og håndtere statistik vha eksporter - på sigt et JSON feed - som kan analyseres og udstilles i en ekstern og målrettet statistikapplikation. 

Hvis det er løsningen, så er næste skridt at udvide de eksisterende eksporter (frivillige og vagter) samt at indføre tre nye (events, opgaver og arrangører). Formålet er at give gode muligheder for at lave relevant statistik og BI på tværs af rapporterne. 

Se et oplæg her, i fanen "Eksporter": https://docs.google.com/spreadsheets/d/1xocGICUCHaEGjVw1L8CM6EqDJ-HtJnThWa0K1uIHVzk/edit?pli=1&gid=1400388749#gid=1400388749.

**Comment by MartinQwist** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
Felter til eksport |   |  
-- | -- | --
  |   |  
Felt | Rapport | Status
Person (for- og efternavn(e)) | Frivillige | Implementeret
Email | Frivillige | Implementeret
Telefon | Frivillige | Implementeret
Bopæl (postnummer) | Frivillige | Implementeret
Fødselsdag (alder i år) | Frivillige | Implementeret
Køn | Frivillige | Implementeret
T-shirt størrelse | Frivillige | Implementeret
Nationalitet | Frivillige | Implementeret
Primært sprog | Frivillige | Implementeret
Taler (Sprogkundskab) | Frivillige | Implementeret
Lables | Frivillige | Implementeret
Medlemsskab (oprettelsesdato) | Frivillige | Implementeret
Sidst set (seneste login) | Frivillige | Implementeret
Person (for- og efternavn(e)) | Vagter | Implementeret
Mail | Vagter | Implementeret
Dato | Vagter | Implementeret
Tidsrum | Vagter | Implementeret
timer | Vagter | Implementeret
ventelister | Vagter | Implementeret
event | Vagter | Implementeret
opgave | Vagter | Implementeret
Fremmøde (ikke registreret/fremmødt/udeblevet/godkendt fravær) | Vagter | Ønske
Vagtsted | Vagter | Ønske
Tidspunkt for publicering af vagt(pakke) | Vagter | Ønske
Tidspunkt for tilmelding/tildeling | Vagter | Ønske
Org navn | Arrangører | Ønske
Postnummer | Arrangører | Ønske
Hovedarrangør, navn | Arrangører | Ønske
Hovedarrangør, mail | Arrangører | Ønske
Hovedarrangør, tlf | Arrangører | Ønske
CVR | Arrangører | Ønske
Eventnavn | Events | Ønske
Eventets arrangør | Events | Ønske
Eventsted (postnummer) | Events | Ønske
Dato for første publicering | Events | Ønske
Dato for seneste publicering | Events | Ønske
Eventdato | Events | Ønske
Opgavetitel | Opgaver | Ønske
Opgavetekst | Opgaver | Ønske
Ejerorganisation | Opgaver | Ønske
(Evt. unikt ID, da opgaver kan have samme titel) | Opgaver | Ønske


</body>
</html>

**Comment by antonlund18** [comment]
Løst i henholdsvis #321, #322, #327 og #328.

Vi har ikke tilføjet publiceringsdatoer i denne omgang. Jeg har oprettet et nyt issue til dette: #329
