### ISSUE TITLE
Deaktivering af frivillig

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#319]
Vi har i Kulturens Frivillig besluttet at deaktivere to brugerprofiler pga. udeblivelser. 

Derfor vil vi gerne kunne deaktivere en bruger. 

Som minimum (must have) vil vi gerne kunne deaktivere en bruger, så vedkommende ikke kan tage flere vagter. Dette løser vores umiddelbare behov. Det kan evt. laves sådan, at en frivillig kun kan deaktiveres, når vedkommende ikke har nogen fremtidige vagter. Dvs. man som frivilligorgansiation skal ind og afmelde den frivillige på eventuelle fremtidige vagter, før den frivillige kan deaktiveres. Det er vigtigt, at den frivillige stadig har sin historik - altså at fortidige vagter ikke slettes. 

Derudover (could have) kan der bygges ekstra funktionalitet, der gør, at man kan deaktivere den frivillige i en fastsat periode (midlertidig karantæne).

**Comment by antonlund18** [comment]
Det viste sig faktisk at være nemmere, at tjekke når en bruger logger ind hos en frivilligorganisation, så jeg er gået med den fremgang i stedet.

Så når en deaktiveret bruger logger ind hos en frivilligorganisation, vil de blive mødt af denne side:
![Image](https://github.com/user-attachments/assets/69532f20-c35d-4fc5-ba80-6b7494d844c6)

Dette er kun hvis de logger ind hos den frivilligorganisation, de er blevet deaktiveret hos. De kan altså bruge siden som normalt, hvis de logger ind hos en anden frivilligorganisation.

Deaktivering følger samme regler som når man prøver at slette en bruger, udover at man ikke kan deaktivere en bruger, der har fremtidige vagter. Hvis det er nemmere at den fjerner brugerne fra vagterne, må i sige til 😊

**Comment by antonlund18** [comment]
P.s. det er kun den hovedansvarlige, der kan deaktivere en bruger lige nu. @MartinQwist er det alle administratorer, der skal have mulighed for at deaktivere brugere?

**Comment by MartinQwist** [comment]
> P.s. det er kun den hovedansvarlige, der kan deaktivere en bruger lige nu. [@MartinQwist](https://github.com/MartinQwist) er det alle administratorer, der skal have mulighed for at deaktivere brugere?

Nej, det er egentlig OK, at det kun er hovedansvarlige. Men kan du i den forbindelse sørge for, at jeg bliver hovedansvarlig i Kulturens Frivillige? Lige nu er det Mikkel, der er det.

**Comment by antonlund18** [comment]
Sådan 😊

**Comment by MartinQwist** [comment]
Er det her?

![Image](https://github.com/user-attachments/assets/b772c367-8b64-4be8-826f-553e3b389068)

**Comment by MartinQwist** [comment]
Nej, det er i Kulturens. Hvis du gør mig til Hovedadmin i preview, så prøver jeg der.

**Comment by MartinQwist** [comment]
Ah, beklager jeg ikke var helt tydelig. 

Til tests mv. ift. udviklignen bruger vi altid Rethinkers preview. Der er ret meget indhold at teste på, nemlig. Og der er Mikkel stadig hovedadmin. 

Men vil du ikke ændre den til at jeg er hovedadmin der?

**Comment by antonlund18** [comment]
Ahh, det giver mening 😊 Det skulle være ændret nu.
