### ISSUE TITLE
Udvidelse af vagt eksport

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#321]
| Felt | Rapport | Status |
|-----|-----|-----|
| Fremmøde (ikke registreret/fremmødt/udeblevet/godkendt fravær) | Vagter | Ønske |
| Vagtsted | Vagter | Ønske | 
| Tidspunkt for publicering af vagt(pakke) | Vagter | Ønske |
| Tidspunkt for tilmelding/tildeling | Vagter | Ønske |

**Comment by antonlund18** [comment]
Jeg tror ikke vi har information omkring publicering af vagtpakken, medmindre man har valgt at den skal publiceres en bestemt dato. Jeg har ikke implementeret den i denne omgang, men hvis det er noget der er vigtigt for jer, synes jeg vi skal bruge noget tid på at implementere det ordentligt.

**Comment by MartinQwist** [comment]
Informationen om publicering af vagtpakken er vigtig i den forbindelse, at vi gerne vil føre statistik på, hvordan tilmeldinger udvikler sig. Fx: Er det en fordel at publicere tre måneder fremfor to måneder før? Hvilke events/opgaver bliver fyldt hurtigt op? Hvornår tilmelder frivillige sig typisk, og varierer det ift. publiceringsdato for events. 

Vi kan vende behov og løsning på et statusmøde. 

Jeg kan ikke se, at nogen af de fire felter er tilføjet til eksporten. Heller ikke fremmøde og vagtsted. Kan det passe?

**Comment by antonlund18** [comment]
Ahh, min fejl. Jeg havde tilføjet den til eksporten af vagtplanen - havde ikke set, der også var en eksport for vagter på tværs af events. Jeg hiver den lige tilbage.

**Comment by antonlund18** [comment]
Så skulle den være der 😊

**Comment by MartinQwist** [comment]
Meget fint. Sindssygt værdifuld viden i den eksport. Sammen med de andre kan vi virkelig lave nogle meget indsigtfulde statistikker. Stærkt!
