### ISSUE TITLE
Tilføj eksport af opgaver

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#328]
Felt | Rapport | Status
-- | -- | --
Opgavetitel | Opgaver | Ønske
Opgavetekst | Opgaver | Ønske
Ejerorganisation | Opgaver | Ønske
(Evt. unikt ID, da opgaver kan have samme titel) | Opgaver | Ønske

**Comment by MartinQwist** [comment]
Den virker. Egentlig fin, men jeg har et par kommentarer:
- Kolonnerækkefølgen skal være: A: Ejerorganisation, B: opgavetitel: C: Ejerorganisation, D: ID. 
- Kan du lave en opgave, som handler om at lave en eksport af alle opgaver i hele frivilligorganisationen inkl. alle arrangører under frivilligorganisationen? Det er egentlig det, jeg har behov for.

**Comment by antonlund18** [comment]
Sådan, så skulle den være der 😊

Er stadig lidt i tvivl om rækkefølgen, så har lavet: A: Ejerorganisation, B: Titel, C: Beskrivelse, D: ID
