### ISSUE TITLE
Undersøg hvad der skal til for at lave custom domains

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#334]

**Comment by antonlund18** [comment]
[Opsætning af custom domæner.docx](https://github.com/user-attachments/files/16985670/Opsaetning.af.custom.domaener.docx)

**Comment by MartinQwist** [comment]
Kan jeg gå videre med at undersøge dette i Kulturens Frivillige ift. kommentarer og præferencer? Eller skal jeg lige vente lidt?

**Comment by antonlund18** [comment]
@MartinQwist Vi har lige fået snakket om den, og jeg tror der er lidt mere arbejde i den. Jeg hiver den lige tilbage igen.

**Comment by henrikbak** [comment]
Skal idéelt set være færdig til første uge af november. Undersøg om det er realistisk.
