### ISSUE TITLE
Ny navngivning til "+ Tilføj filter"

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#347]
Omdøb knap til 'Vælg modtagere' og default til at ingen modtagere er valgt.

### Discussed in https://github.com/orgs/xooom-community/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **MartinQwist** September 12, 2024</sup>
Jeg har hørt fra nogle arrangører, der går i stå ift. vores beskedfunktion. De prøver lidt, bliver usikre, går i stå og spørger mig, hvor de kan finde de frivilliges e-mail adresser. 

En af de ting, der får igen hos dem, der ikke kan lure funktionen er feltet "+ Tilføj filter". De forstår ikke, hvad den gør. De vil gerne vælge (flere) modtagere - og ikke tilføje filtre. 

Kan knappen evt. omdøbes til "Vælg modtagere"? 

![image](https://github.com/user-attachments/assets/3ff2dc4b-2d2f-4f77-b30f-8759330891b7)
</div>

**Comment by MartinQwist** [comment]
Yes, helt perfekt. Jeg så lige en detalje, som du måske kan rette til? 

Som arrangør kan jeg bruge "Vælg modtagere"
![Image](https://github.com/user-attachments/assets/deff35e6-48cf-46d6-bbda-fabe1987526a)

Vælger jeg "Brugere" får jeg lov til at tilføje administratorer. 
![Image](https://github.com/user-attachments/assets/58885016-a2e8-4596-a0ea-17f141e6b306)
![Image](https://github.com/user-attachments/assets/805713ef-9149-463e-9706-0bd708f2e90a)

Jeg tænker, at "Brugere" skal omdøbes til "Administratorer"?

**Comment by antonlund18** [comment]
Brugere er både administratorer og frivillige. Jeg antager at 'Lystrup rostævne' er en arrangør, og derved ikke har nogle frivillige.
