### ISSUE TITLE
Afvis arrangør

### ISSUE THREAD

**Issue by henrikbak** [xooom-community/product#355]
Det skal være muligt at afvise en arrangøransøgning. Det ser ud til at der er laves resolvers og logik til det, men at det aldrig er koblet sammen med frontenden.

Der ligger også en mailskabelon klar. Test at hele flowet fungerer.

**Comment by MartinQwist** [comment]
Jeg kan ikke teste denne i preview, for jeg kan ikke oprette en ny arrangør. Jeg kan ikke komme videre herfra:

![Image](https://github.com/user-attachments/assets/5e08a092-1f37-4b39-80c1-a78f61990b58)

![Image](https://github.com/user-attachments/assets/d27ced9c-cacf-4eba-b0b1-da63582b4b92)

Når jeg trykker "Fortsæt",  så sker der ikke noget...

**Comment by antonlund18** [comment]
Der manglede et redirect tilbage til oversigten over ens ansøgninger - det er fixet nu

**Comment by MartinQwist** [comment]
Hmmm. Jeg går stadig i stå her i oprettelsesflowet. Jeg modtager ingen bekræftelsesmail og arrangøransøgningen dukker heller ikke på hos frivilligorganisationen. 

![Image](https://github.com/user-attachments/assets/7a7cf76e-454d-401c-885b-ab05f7fb4632)

**Comment by antonlund18** [comment]
Ahh, jeg tror det er noget helt andet. Det er vist når man angiver en lokation uden længde- og breddegrader. Prøv at angive dem i din adresse, og så kan du forhåbentligt afvise nazierne 😁

Jeg har oprettet et issue på at fikse det: #360

**Comment by MartinQwist** [comment]
OK, det virkede. Fint, at der er oprettet et issue på at rette det. 

Det lader til, at jeg mister adgangen til frivilligorganisationen, når jeg opretter en ny arrangør:

![Image](https://github.com/user-attachments/assets/ba1d8116-6433-47c4-ae76-13c2ce245543)
![Image](https://github.com/user-attachments/assets/5a32e8c8-7119-4f75-8873-ddea44dcacb4)


Det er vel en bug? 

Jeg har jo behov for adgang til frivilligorganisationen for at kunne teste afvisningen. Men derudover, tænker jeg også, at det er en use case, der let kunne forekomme i praksis.

**Comment by MartinQwist** [comment]
@antonlund18 Jeg har stadig ingen arrangøradgang til preview.

**Comment by antonlund18** [comment]
Jeg kigger på det. Du kan godt logge ind på preview.rehelper.dk/dashboard, ikke? Det er bare på denne her liste, du ikke kan se det, right?

**Comment by antonlund18** [comment]
Jeg har lige deployed, så den også vises på listen. Men hvis du ikke kan logge ind på dashboardet, lyder det til, at der er noget helt andet galt.

**Comment by MartinQwist** [comment]
> Jeg kigger på det. Du kan godt logge ind på preview.rehelper.dk/dashboard, ikke? Det er bare på denne her liste, du ikke kan se det, right?

Nope, jeg kan slet ikke logge ind på frivilligorganisationen på Rehelper med min bruger mqwist@gmail.com. Jeg burde være hovedarrangør i frivilligorganisationen. Jeg kan slet ikke komme ind. Kun på mine arrangørorganisationer. 

Jeg opdagede det første gang lige efter jeg havde oprettet en ny organisation, som jeg ville prøve at afvise med den nye funktion.

**Comment by MartinQwist** [comment]
Så er jeg tilbage, og afvis-funktionen fungerer fint. 

Som afvist får man denne mail:

![Image](https://github.com/user-attachments/assets/b48edba3-7c88-4f58-82de-a57e65a9229c)

Jeg antager, at det er en af de automails som frivilligorganisationen selv skal formulere tekst til. I så fald helt fint.
