### ISSUE TITLE
Lokationsfejlmelding når man ansøger om at blive arrangør

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#360]
Når man ansøger om at blive arrangør, kan man ikke fortsætte, hvis man har angivet en lokation uden længde- og breddegrader, men man får ingen besked om fejlen. Lav passende fejlbeskeder, når ansøgning fejler. 

Se `become-organizer.tsx`

Ryk direkte i produktion, når færdig.

**Comment by henrikbak** [comment]
Det er nu muligt at lave en lokation uden længe og breddegrad. Det eneste der er påkrævet er et navn på lokationen.
