### ISSUE TITLE
Dato range på eventeksport

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#362]
Man kan lige nu eksportere en oversigt over events.

Oversigten er imidlertid todelt - aktuelle og tidligere - så man skal lave to downloads for at downloade alle events. 

Da formålet med at downloade oftest vil være at lave en form for statistik, overblik mv., så vil det være hensigtsmæssigt at man kan downloade alle events i et time span. 

En løsning kunne være, at man kan sætte et timespan for de events, man gerne vil downloade.

**Comment by henrikbak** [comment]
Jeg har tilføjet et "Alle" filter på eventlisten, så man har kommende, tidligere og alle. Det er en simpel løsning på problemet, men så længe man kan tage alle events, vil man kunne foretage sin filtrering på dato efter man har eksporteret.

**Comment by MartinQwist** [comment]
Ja, selvfølgelig. God løsning.
