### ISSUE TITLE
Som Kræwer skal jeg udfylde udvidet informationer om min profil, første gang jeg tilmelder mig et konkret event

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#379]
Baggrund: I oprettelsen af sin Kræw-profil udfylder man kun de allervigtigste informationer jf. #392  

For at denne User Story er løst: 
- Skal man FØRSTE gang man tilmelder sig et konkret event, udfylde: Skostørrelse, T-shirtstørrelse og højde. 
- Informationerne skal derefter automatisk tilkobles informationerne fra #392 inde på vedkommendes profil. På denne måde er det kun til allerførste tilmelding af et event, at disse oplysninger skal udfyldes. 

Årsagen til at vi ønsker at gøre det på denne måde, er at vi ønsker at kunne minimere antallet af klik og mængden af information man skal udfylde inden vi har dem inde på siden og på den måde minimere hvor mange der "går kolde" i oprettelsesfasen.

**Comment by henrikbak** [comment]
OBS: VI er blevet enige med Emma om at vi flytter disse felter hen til de andre profiloplysninger, som man skal angive ifm. oprettelse, da det spiller bedre sammen med hvordan brugeroprettelsen fungerer i dag.

Vi kan vurdere senere om der er et behov for at vente med at udfylde udvalgte profilfelter til man signer op til et event, men lige nu skaber det bare unødvendig kompleksitet.
