### ISSUE TITLE
Som frivillig skal jeg kunne oprette mig som frivillig i systemet

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#392]
Som frivillig skal jeg kunne oprette mig i systemet. Når jeg har udfyldt mine personlige oplysninger og har givet adgang til at MSF må hente mine straffe- og børneattest, bliver jeg oprettet i systemet. Jeg skal altså IKKE godkendes af en administrator før min profil er oprettet. 

I oprettelsen skal jeg tilføje:

- [x] - Fulde navn 
- [ ] - CPR-nummer
- [x] - E-mail
- [x] - Adresse
- [x] - Telefonnummer
- [x] - Ønsket adgangskode
- [x] - En boks hvor jeg kan afkrydse "Hemmelig adresse"
- [x] - En boks hvor jeg kan afkrydse "hemmelig telefonnummer"
- [ ] - En boks hvor jeg kan give samtykke til at MSF må indhente min straffe- og børneattest. 

UPDATE:
Følgende felter tilføjes også til profilen jvf. #379 

- [x] - Skostørrelse
- [x] - T-shirtstørrelse
- [x] - Højde

**Comment by henrikbak** [comment]
@EmmaIsager Er det rigtigt forstået at tilmeldingen som frivillig er noget man gør adskilt fra selve tilmeldingen som frivillig på et bestemt event, som eksempelvis Grøn Koncert 2025. Jeg forestiller mig det sådan her:

1. Jeg ønsker at blive frivillig: Jeg udfylder tilmeldingsformularen på kraewet.dk og får en bruger i systemet. Nu er jeg en del af databasen af frivillige i Kraewet.
2. Jeg ønsker at være frivillig på et event: Jeg logger ind på kraewet.dk med min bruger og finder det event jeg vil detage i (Eksempelvis Grøn Koncert 2025). Jeg anmoder om at blive frivillig på eventet jvf. #374.

**Comment by EmmaIsager** [comment]
Hej Henrik

Sådan som du forklarer det herunder er nemlig helt rigtigt sådan vi gør det i vores nuværende system. Det kunne vi godt tænke os at bevarer, men at have mere fokus på kommunikationen og brugerrejsen i forhold til at gøre det tydeligt at man ikke er tilmeldt et event efter første step. Det kan vi muligvis tale om til mødet senere i dag 😃

De bedste hilsener /
With kind regards

Emma Isager Clausen
Frivillighedskoordinator og
lokalforeningsansvarlig på Grøn koncert

Mobil: 61240247
Tlf. 8948 2222
Muskelsvindfonden
Kongsvang Allé 23
8000 Aarhus C


Fra: Henrik Lund Thomassen ***@***.***>
Sendt: 9. oktober 2024 14:19
Til: xooom-community/product ***@***.***>
Cc: Emma Sofie Isager Clausen ***@***.***>; Mention ***@***.***>
Emne: Re: [xooom-community/product] Som frivillig skal jeg kunne oprette mig som frivillig i systemet (Issue #392)

[EKSTERN AFSENDER] Tryk ikke på links eller filer, med mindre du stoler på afsenderen, og ved at det er sikkert.

@EmmaIsager<https://github.com/EmmaIsager> Er det rigtigt forstået at tilmeldingen som frivillig er noget man gør adskilt fra selve tilmeldingen som frivillig på et bestemt event, som eksempelvis Grøn Koncert 2025. Jeg forestiller mig det sådan her:

  1.  Jeg ønsker at blive frivillig: Jeg udfylder tilmeldingsformularen på kraewet.dk og får en bruger i systemet. Nu er jeg en del af databasen af frivillige i Kraewet.
  2.  Jeg ønsker at være frivillig på et event: Jeg logger ind på kraewet.dk med min bruger og finder det event jeg vil detage i (Eksempelvis Grøn Koncert 2025). Jeg anmoder om at blive frivillig på eventet jvf. #374<https://github.com/xooom-community/product/issues/374>.

**Comment by henrikbak** [comment]
@EmmaIsager Kan du forklare hvad "Hemmelig adresse" og "Hemmelig telefonnummer" betyder helt konkret. Jeg er med på at det kan betyde man skjuler disse oplysninger for nogen, men hvem må se oplysningerne, når oplysningerne er hemmelige?

**Comment by EmmaIsager** [comment]
@henrikbak Oplysningerne skal kun kunne ses af de profiler med rollen "MSF Administrator". Det vil sige ingen sektionschefer eller Kræwere skal kunne se det.

**Comment by EmmaIsager** [comment]
Endnu en ting @henrikbak. Vi snakkede om at ændre i informationen som man skal oprette sig med. Jeg ændrer ikke i User stories når I først rykker dem over i "In Progress" men jeg tænker du kan huske de ting du selv foreslog omkring oprettelsen og så kan vi teste det af om det fungerer når tiden er til det 👍

**Comment by henrikbak** [comment]
@EmmaIsager Jeg tager lige CPR-nummer og samtykke ud af denne opgave, da det afhænger af noget indledende afklaring. Så blokerer det ikke for at vi kan få resten af funktionen skubbet videre i processen.

#443

**Comment by EmmaIsager** [comment]
Evalueringspunkter fra Review: Som vi talte om, fjerner vi under oprettelsen, at man kan sig via Google og MitID, for ikke at komme til at dublere allerede eksisterende profiler når vi overfører dem fra det gamle til det nye system.

**Comment by EmmaIsager** [comment]
Perfekt! Jeg synes det er super fint, at I vurderer hvilke af evalueringspunkterne fra Preview-snakkede der lige hurtigt kan fikses og hvilken der kræver en helt ny User story.

**Comment by EmmaIsager** [comment]
@antonlund18  og @henrikbak  Vi talte om at informationen skal være obligatorisk at udfylde. Det hører under denne, ik?
