### ISSUE TITLE
Flet spørgeskema fra frivilligorganisation sammen med spørgeskema fra arrangør

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#397]
Mangler afklaring.
 
- Skal frivilligorganisation se data fra arrangørs spørgeskema?
- Skal arrangør se data fra  frivilligorganisations spørgeskema?

**Comment by MartinQwist** [comment]
> Mangler afklaring.
> 
> * Skal frivilligorganisation se data fra arrangørs spørgeskema?
> * Skal arrangør se data fra  frivilligorganisations spørgeskema?

Ja. Arrangører skal ikke kunne skjule svar fra frivilligorganisationen. 

Som hovedregel ja - på nær når et spørgsmål fra en frivilligorganisation er skjult for arrangører.

**Comment by antonlund18** [comment]
Løst i #73
