### ISSUE TITLE
Opret holdpakker

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#409]

**Comment by antonlund18** [comment]
![Image](https://github.com/user-attachments/assets/b338213f-6ea4-4be8-bd90-247261acde7e)

**Comment by EmmaIsager** [comment]
Når man laver en ny holdpakke kunne det være godt og brugervenligt hvis “ny opgave”-knappen var allerøverst i stedet for under alle holdforslagene man kan vælge.
