### ISSUE TITLE
Som [alle roller] skal jeg kunne logge ind på min personlige profil

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#423]
Ligegyldig hvilken rolle jeg skal have, skal jeg kunne logge ind på min personlige profil ved hjælp af:
- Min E-mail 
- En adgangskode jeg selv valgte da jeg oprettede mig

Login-delen skal også have en knap hvor man kan trykke "Jeg har glemt adgangskode". 

Selve layoutet på siden skal nudge til selvhjælp hvis man har glemt sin kode, så vi undgår at modtage mange mails fra Kræwere, som ønsker at vi går ind og nulstiller deres adgangskode for dem.

**Comment by henrikbak** [comment]
@EmmaIsager Dette understøtter systemet allerede, så jeg tænker bare at vi lukker opgaven her. Du kan se et screenshot af vores loginformular her:

![Image](https://github.com/user-attachments/assets/26c6145c-6a4f-454c-9260-7133eab167cc)

**Comment by EmmaIsager** [comment]
@henrikbak, super fint! Og så kan vi gøre den mere Kræwagtig på sigt og evt. fjerne det med "log ind med Google eller MitID"
