### ISSUE TITLE
Som MSF Admin, vil jeg gerne kunne oprette flere dato-detaljer i tilmeldingen til et event

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#430]
Relateret til https://github.com/xooom-community/product/issues/351

Når man som Kræwer skal tilmelde sig et event, skal det være nemt og overskueligt at se hvad man præcis tilmelder sig. 
Hvilken dato er det? 
Hvilken ugedag er det?
Hvilket ugenummer er det
Hvilken koncertby er det? 

Derudover skal man som Kræwer kunne se de samme detaljer for "datopakker" (altså halvturs og helturs) og ikke kun for enkeltdage. Dermed kan man nemt kan få overblik over hvilke datoer, ugedage, ugenummer og koncertbyer man har tilmeldt sig, lige meget om det kun er en enkelt dag, en halv tur eller hele turen. 

Denne opgave er løst når:
- Jeg som MSF Admin har mulighed for at gå ind og udfylde disse detaljer i oprettelsen af et event, ligesom jeg også skal have mulighed for redigering af detaljerne i et allerede oprettet event. 

- Jeg som MSF Admin har mulighed for at kunne gruppere enkelte koncertdage. Eksempelvis skal jeg kunne gruppere 1. halvdel af turen, 2. halvdel af turen og hele turen i "datopakker" hvor dato, ugedag, ugenummer og koncertby tydeligt fremgår når man tilmelder sig.

**Comment by antonlund18** [comment]
Jeg har tilføjet følgende på event-siden:
![Image](https://github.com/user-attachments/assets/2686baa9-b615-41e9-bd03-4c2a6e7b0e65)

Ugedag og ugenummer tænker jeg er noget vi automatisk udregner ud fra datoen, og viser i portalen, når de frivillige skal tilmelde sig.

**Comment by EmmaIsager** [comment]
Preview fra d. 13.01 @antonlund18 @henrikbak 
Jeg er ikke sikker på om den hører hjemme her, men så flytter vi den. 

Når man først har oprettet datoer på et event og sætter det i produktion kan man ikke redigere i datoerne? Jeg har sat billede ind af det sted jeg taler om.

![Image](https://github.com/user-attachments/assets/5f339fd0-eab1-4cca-9ce4-82d820e2b0b1)
