### ISSUE TITLE
Som Kræwer kan jeg nemt og overskueligt prioritere tre sektioner når jeg ønsker at tilmelde mig et åbent event

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#431]
Relateret til https://github.com/xooom-community/product/issues/351

Vi har 41 mulige sektioner på Grøn. 

Når jeg som Kræwer tilmelder mig, skal det være nemt at overskue alle sektionerne, så jeg ikke blot ender med at vælge blandt de sektioner der tilfældigvis ligger øverst, fordi det er nemmest. Det skal også være nemt at finde sektioner som kan matche mine interesser og kompetencer. Når jeg har prioriteret 3 sektioner, skal jeg vente på at en sektionschef tilføjer mig til sin sektion. Jeg er altså tilmeldt eventet, men jeg er ikke blevet tilmeldt en konkret sektion endnu.

Denne opgave er løst når:
- Når man som Kræwer kan vælge relevante tags, som kommer til at danne basis for en filtrering på sektionsoversigten ("multifaceteret filtrering").

**Comment by antonlund18** [comment]
![Image](https://github.com/user-attachments/assets/df6825d7-1b12-4107-834e-26b533553d6b)
![Image](https://github.com/user-attachments/assets/f77a32c5-8e07-42a6-9da8-87d600d67454)

**Comment by antonlund18** [comment]
Mangler at sektionerne bliver sorteret efter største mangel på frivillige, da den afhænger af nogle andre opgaver. Jeg har oprettet et seperat issue på denne: #451

**Comment by EmmaIsager** [comment]
Evalueringspunkter fra Preview d. 08.11.24: 
1. Under “Hvilket hold vil du på?” i tilmeldingen til et event, skal der være mulighed for at MSF Admin kan skrive en lille tekst som gør det klart at det kun er ønsker til sektion og at det ikke er sikkert man får sin ønsker opfyldt, for at forventningsafstemme på forhånd.

**Comment by antonlund18** [comment]
Det er lidt af en større opgave at give MSF Admin's lov til selv at kunne definere og rette i teksterne inde i systemet - og lidt overkill at lave lige nu, hvor i også er den eneste festival vi har i systemet. Så jeg har oprettet den som en opgave, og tænker det er noget vi kan lave i version 2.0 (eller hvornår det nu giver mening: #455.

Indtil da, vil du så ikke forsyne os med en tekst, som jeg kan proppe ind? I må gerne gøre den specifikt for hvordan i rekrutterer frivillige, men helst så generel at den i princippet kunne bruges af andre, hvis nu de tilfældigvis også rekrutterede på samme måde (altså; undgå ord som Kræwet/Grøn Koncert/MSF).

**Comment by EmmaIsager** [comment]
Du har helt ret. Det er ikke nødvendigt at MSF Admin kan redigere i dette, da informationen er uafhængig af eksempelvis hvilket år vi er i eller lignende, så det er så fint. 

Jeg tænker overskriften (der hvor der nu står "hvilket hold vil du på?") skal være: ""hvilket hold ønsker du at komme på?"

Og så teksten nedenunder hvor der lige nu står "vælg 3 hold i prioriteret rækkefølge" skal være: Herunder skal du prioritere tre hold. Din 1. prioritet er det hold du helst vil være en del af. Dit valg er et ønske og ikke et krav, så selvom vi vil gøre hvad vi kan for at opfylde et af dem, er det ikke noget vi kan garantere."

Lad os prøve dette og så må vi ændre senere hvis det ikke fungerer.
