### ISSUE TITLE
Som Kræwer skal jeg nemt kunne tilgå uddybet information om de forskellige sektioner, som jeg har mulighed for at prioritere i min tilmelding

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#434]
Når jeg som Kræwer skal prioritere tre sektioner i min tilmelding til et event, skal jeg kunne trykke et pop-up vindue frem ved hver sektion, som beskriver sektionen mere i dybden, så jeg som Kræwer har en større forståelse for de sektioner jeg vælger at prioritere i min tilmelding.

**Comment by antonlund18** [comment]
![Image](https://github.com/user-attachments/assets/df6825d7-1b12-4107-834e-26b533553d6b)
![Image](https://github.com/user-attachments/assets/f77a32c5-8e07-42a6-9da8-87d600d67454)
