### ISSUE TITLE
Som Kræwer vil jeg gerne let kunne omarrangere blandt mine 3 prioriteter ved tilmelding

### ISSUE THREAD

**Issue by EmmaIsager** [xooom-community/product#437]
Når jeg har valgt sektioner, lægger de sig pænt på min prioriteringsliste. For at skifte prioritet er jeg nødt til at slette mine valg og vælge til igen i korrekt rækkefølge. Det kunne være smart, hvis man let kunne omarrangere blandt de valgte.
Fx med drag'n'drop eller lignende.

**Comment by antonlund18** [comment]
![Image](https://github.com/user-attachments/assets/df6825d7-1b12-4107-834e-26b533553d6b)
![Image](https://github.com/user-attachments/assets/f77a32c5-8e07-42a6-9da8-87d600d67454)

**Comment by EmmaIsager** [comment]
Evalueringspunkter fra Preview d. 08.11.24: Vi fjerner "slå manuel udvælgelse til” fra, da vi vurderer at det er en funktion vi ikke har behov for og at den vil forvirre Kræwerne i tilmeldingsprocessen.

**Comment by antonlund18** [comment]
> Evalueringspunkter fra Preview d. 08.11.24: Vi fjerner "slå manuel udvælgelse til” fra, da vi vurderer at det er en funktion vi ikke har behov for og at den vil forvirre Kræwerne i tilmeldingsprocessen.

Denne er lavet
