### ISSUE TITLE
Som MSF Admin kan jeg tilføje nye tags, redigere og slette i eksisterende tags på mine sektioner

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#442]
Eksempler på tags er:
- Mindre søvn
- Publikumskontakt
- Hårdt fysisk

**Comment by antonlund18** [comment]
![Image](https://github.com/user-attachments/assets/aa1eb834-277c-49b8-ad94-d2858f155aac)

**Comment by antonlund18** [comment]
@EmmaIsager Jeg har lidt problemer med, at jeg kun kan uploade videoer på 10 MB eller mindre, så jeg kan ikke rigtigt sende en video til det her...

**Comment by EmmaIsager** [comment]
@antonlund18 Alt godt hvis vi bare får et par screenshots, så ser vi om det ikke er tilstrækkeligt 👍
