### ISSUE TITLE
Ændre KF logo på rehelper.dk

### ISSUE THREAD

**Issue by MartinQwist** [xooom-community/product#467]
Vi har i Kulturens Frivillige fået nyt logo. Vil I ændre vores logo på rehelper.dk til dette? 

![Image](https://github.com/user-attachments/assets/e79d1f0f-4fba-4dfe-b20c-b5ade41df6cf)

**Comment by henrikbak** [comment]
@MartinQwist Fandt du af den her? I kan selv ændre logoet

Jeg lukker den her, og så må du åbne den igen, hvis der er spørgsmål

**Comment by henrikbak** [comment]
Jeg læste den lige igen, og nu forstår jeg hvad du skriver :) 

Vi skal nok får indsat logoet på rehelper.dk
