### ISSUE TITLE
Signon og login flow

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#47]
- Signon og login kan opleves som besværligt (hvor er "Jeg har glemt mit kodeord", navngivning, forvirrende med send link.) Vi ønsker et nyt/forbedret flow.
- Det er forvirrende, når man linker til undersider (vagter, events, grupper), men når man bliver bedt om at logge ind, så havner man på hovedportalen. Man skal gerne kunne fortsætte til den underside, man er på vej ind til.

**Comment by mikkelsl** [comment]
Har arbejdet på den her hele weekenden. Vildt kompleks at simplificere den, men når først den falder på plads, så bliver det virkelig godt.
Har forsøgt at smelte log ind og oprettelse sammen - ligesom Airbnb. Derudover har vi opbygget en del løse login funktioner, som er blevet slået sammen til et enkelt powerfuldt komponent.

Tænker godt vi kan ramme nogle edge cases endnu, men mon ikke resultatet er bedre end den eksisterende løsning allerede.

Mangler:

- [ ] Test at login med magiclink fungerer optimalt
- [ ] Ved login på email, der ikke har adgangskode, vis mulighed for oprettelse af bruger
- [ ] Test MitID med og uden tilknytning grundigt
- [ ] Mere?

**Comment by mikkelsl** [comment]
"Bliv arrangør" knappen er flyttet ind under "Arrangører" i samme forbindelse. Øverst til højre i navigationen reserveres til kun at være brugerens afdeling, så vi også får plads til flere muligheder senere.

**Comment by mikkelsl** [comment]
Flowet for en ny bruger, hvis de indtaster email er ikke helt optimalt, fordi de skal læse og trykke på teksten: "Er du en ny bruger? Opret bruger", som står under indtast adgangskode. Hvis vi tjekker, om de har en bruger i forvejen, går vi til gengæld på kompromis med sikkerhed. Airbnb gør det, men de er måske også helt anderledes gearet til at forebygge angreb, end vi er.

For at få den her store opdatering ud og komme videre, foreslår jeg, at vi udgiver det som det er, og vender tilbage til det senere. Jeg tænker ikke at oplevelsen er væsentlig dårligere end tidligere. Til gengæld er der lavet mange andre tiltag, der løfter hele brugeroplevelsen.

**Comment by mikkelsl** [comment]
Jeg har flyttet "Bliv frivillig" formularen, så du får den som popup, du ikke kan lukke, så snart du er logget ind og ikke har ansøgt som frivillig. Du kan altså ikke gøre andet. Når du har ansøgt, kan du heller ikke komme videre uden at verificere med MitID eller afvente accept af admin.

Det kan godt være, det er lidt for voldsomt, men jeg har gjort det for at kunne udgive denne feature med nogenlunde ro i sindet. Der er lavet en del forbedringer af opbygningen af koden, logik osv. ifm. den her feature, så jeg vil bare gerne have den ud i en version, der virker.

Test, kom med feedback, og lad os få den til at sidde i skabet. Vores brugerstyringsflow har i hvert fald taget et stort spring bag scenen.

**Comment by MartinQwist** [comment]
Jeg har testet lidt, så godt jeg kunne. Jeg er slet ikke kommet hele vejen rundt, men alt jeg stødte på virkede og systemet gjorde, som jeg forventede.
