### ISSUE TITLE
Ændring af vagttidspunkt

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#48]
Flere af de første arrangører på Rehelper efterlyser, at man kan ændre tidsrummet for en vagt. Det samme er nødvendigt for at kunne koordinere krydstogtanløb - som både Nyborg og Aarhus gør - hvor anløbene ofte ændrer tidsrum. 

Dette udfordrer imidlertid systemlogikken. 

Jeg er kommet på et kompromis, som kan virke forretningsmæssigt og - tror jeg - også teknisk:

Det skal altid være muligt for arrangøren at forkorte en vagt indenfor vagtens eksisterende tidsrum. Dette følger de øvrige godkendelsesregler.
Det skal være mugligt at redigere tidsrum for vagter i en kladdetilstand så længe eventet ikke er sendt til godkendelse eller udgivet. Når et event udgives første gang, så låses vagterne i de angivne tidsrum, som er angivet

Rethinker insisterer desuden på, at der skal være en systemunderstøttet måde, hvorpå man som arrangør kan flytte et vagttidspunkt indenfor samme dag. De påpeger i den forbindelse, at dette er normalt i al frivillighåndtering - særligt når vi beder arrangørerne om at være klar med opgavebeskrivelser og vagtplaner i god tid. Derfor ser Rethinker fortsat følgende som vigtigt: 

Når arrangøren ændrer et vagttidspunkt til at slutte senere og/eller starte tidligere, så skal dette først godkendes af frivilligorganisationen (efter normale godkendelsesflow - manuel eller auto) og dernæst skal forlængelsen accepteres af den frivillige inden tilmelding luk. Hvis den frivillige ikke accepters, så frameldes den frivillige ved tilmelding luk. Hvis det afvises, så frameldes den frivillige. 

- [x] #350
- [x] #352
- [x] #353
- [x] #357
- [x] Sørg for at logikken kan adskilles fra ventelister

**Comment by mikkelsl** [comment]
Ved udvidelse af vagttid vil man umiddelbart sætte status for hver frivillig som "ubekræftet" - det skal laves på en måde, så venteliste ikke kan smide folk af. Der er behov for samme logik ved ændring af opgave på en vagt, se her: https://github.com/xooom-community/product/issues/17#issuecomment-2082519342

**Comment by MartinQwist** [comment]
Bemærk, at der kan være noget logik, der kan genbruges fra #210 . Evt. ift. "Frivillig skal godkende, hvis vagttidspunktet ændres". Hvis ikke, så er det nok en relevant sondring.
