### ISSUE TITLE
Spørgeskemaer v2

### ISSUE THREAD

**Issue by antonlund18** [xooom-community/product#486]
Sidste rettelser

- Eksport
- Skjul for arrangører
- Tesktfelt

**Comment by antonlund18** [comment]
@MartinQwist Jeg har tilføjet de ovenstående funktioner nu, og så er det også muligt at ændre rækkefølgen af spørgsmål.

**Comment by MartinQwist** [comment]
Det ser for mig ud som om, at det virker efter hensigten. Der kan være noget med navngivning og teksten bag informationsikonet. Men det tager vi lige, når vi har prøvet det af i praksis.

En lille ting: Funktionen "Skjult for partnere" er udelukkende for frivilligorganisationen, så man kan skabe diskretion omkring tilbagemeldinger fra frivillige. To ting: 

- Lige nu kan arrangører vælge "Skjult for partnere". Det skal de ikke kunne. 
- Brugerne skal gerne vide, at de svarer på et "Skjult for partnere"-spørgsmål, og at dette ikke videresendes til arrangøren. En workaround er, at skrive det i spørgsmålsteksten. Men er der andre måder, en frivillig kan se det på? 
- Vi talte om sidst, at spørgeskemaet med fordel kunne indledes med et fast tekstfelt, der beskriver spørgeskemaet (f.eks. også konceptet med, at resultater deles undtaget skjulte felter). Det er så vidt jeg kan se, ikke implementeret? 

Arrangører kan vælge skjult spørgsmål: 
![Image](https://github.com/user-attachments/assets/011b1cec-d727-4578-978a-ab93e5854073)

Fast tekstfelt til kort rubrik under overskriften er ikke implementeret (forslag til placering):
![Image](https://github.com/user-attachments/assets/a80844f0-f687-4cd9-ad4a-ef75ae4542e1)

**Comment by antonlund18** [comment]
> Lige nu kan arrangører vælge "Skjult for partnere". Det skal de ikke kunne.

Hmm, det kunne godt virke til at du stadig ser den gamle udgave. Kan du godt omarrangere spørgsmålene og tilføje brødtekster? Jeg kan fx ikke se 'Skjul for partneren' knappen for denne her arrangør.

Jeg har lige prøvet at deploye igen. Det kan være det hjælper på det.

> Brugerne skal gerne vide, at de svarer på et "Skjult for partnere"-spørgsmål, og at dette ikke videresendes til arrangøren. En workaround er, at skrive det i spørgsmålsteksten. Men er der andre måder, en frivillig kan se det på?

Jeg tror ikke helt, det er noget brugerne bare forstår med et kort lille skriv - og i mange tilfælde er den frivillige måske også ligeglad med hvem der kan se besvarelsen. Jeg tænker den kan løses med en brødtekst i starten af spørgeskemaet til at starte med, og så kan vi måske vende tilbage til den, hvis der opstår behov for den.

> Vi talte om sidst, at spørgeskemaet med fordel kunne indledes med et fast tekstfelt, der beskriver spørgeskemaet (f.eks. også konceptet med, at resultater deles undtaget skjulte felter). Det er så vidt jeg kan se, ikke implementeret?

Jeg har tilføjet et spørgsmålstegn der hvor man kan vælge organisation, der forklarer konceptet lidt.

**Comment by MartinQwist** [comment]
Ja, nu virker det. Jeg kan følge alle dine kommentarer. Afsted med den.

Godt arbejde!
