### ISSUE TITLE
Arrangøransøgning oplysninger

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#50]
Små ændringsønsker:

- [x] "Indtast dine organisationsdetaljer og ansøg om at blive partner med Rethinker Aarhus." ændres til "Indtast dine organisations detaljer og ansøg om samarbejde med Rethinker Aarhus."
- [x] "Arrangørnavn" ændres til "Organisationens navn"

Følgende felter skal tilføjes:

- [x] Brugeren bliver selv sat til VOLUNTEERING_COORDINATOR med sin organizerUser
- [x] Hjemmeside backend (website tilføjet til "createOrganizer")
- [x] Adresse backend (location tilføjet til "createOrganizer")
- [x] CVR backend (cvr tilføjet til "createOrganizer")
- [x] Mulighed for at ændre VOLUNTEERING_COORDINATOR(s) i backenden
- [x] Hjemmeside (ikke obligatorisk)
- [x] Adresse (obligatorisk)
- [x] CVR (obligatorisk) -- (8 talcifre) afkrydsningsfelt skal tilføjes: "Jeg har ikke CVR-nummer." F.eks. til privatpersoner, uformelle netværk og udenlandske organisationer. Arrangøren skal kunne vælge feltet CVR, hvor CVR angives. Eller feltet "Privatperson" hvor privatpersonens navn angives (ikke CPR).
- [x] Vi ved at brugeren har indtastet navn og mail, hvis de mangler telefonnummer, burde vi opfordre dem til at indtaste det i formularen (evt. ligesom ved frivilligansøgninger)
- [x] Ændring af VOLUNTEERING_COORDINATOR i adminpanel -- (liste af coordinators: organizer->coordinators) -- (mutation: organizerUser->updateCoordinator)
- [x] Vis navn og mail på VOLUNTEERING_COORDINATOR(s) under organisationsprofil
- [x] Vis cvr, website, adresse i arrangøransøgning

**Comment by MartinQwist** [comment]
Kontaktperson og email (minimum) skal være obligatorisk, og vises i organisationsprofilen. Arrangører skal have tydeliger kontaktoplysninger tilknyttet deres organisation, så man på rehelper som frivillig kan finde kontaktoplysnigner på arrangøren.

**Comment by MartinQwist** [comment]
`5. CVR skal tilføjes (8 talcifre). Obligatorisk. Afkrydsningsfelt skal tilføjes: "Jeg har ikke CVR-nummer." F.eks. til privatpersoner, uformelle netværk og udenlandske organisationer. `

Arrangøren skal kunne vælge feltet CVR, hvor CVR angives. Eller feltet "Privatperson" hvor privatpersonens navn angives (ikke CPR).

**Comment by mikkelsl** [comment]
"website" tilføjet til companyInformation i backend, ellers er der bare udvidet "createOrganizer" og partner.model
