### ISSUE TITLE
Adgang til holdchats for arrangører

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#53]
Hold er tilknyttede events. Holddeltagere er frivillige på vagter, der er lagt ind under holdet.

Som arrangør har man behov for at kunne deltage i holdchats. Dette besværliggøres umiddelbart af, at det kun er deltagere på holdet, der deltager i chatten. 

Den nuværende workaround er, at man opretter en opgave med 1-2 vagter, som man sætter 1-2 arrangører på - dvs. en fake arrangøropgave. Dermed vil arrangørerne deltage i holdchatten. Men det vil skabe problemer ift. statistik, kommunikation mv.

Der er behov for en mere permanent og integreret løsning på, hvordan arrangører kan deltage i holdchats. Det må gerne være en default, at alle arrangører har adgang til alle holdchats til alle arrangørens events. Det kunne også være en særlig tilmelding til hold for arrangører, så de kan tilmelde sig et hold/holdchat eller lade være.

**Comment by mikkelsl** [comment]
Vi laver en knap ud for hvert hold, hvor der står "X beskeder", som man kan åbne, se og skrive i.

**Comment by MartinQwist** [comment]
Jeg kan ikke lige se, hvordan denne er løst? Hvordan kommer jeg som arrangør ind på en holdchat?

**Comment by mikkelsl** [comment]
Tryk på knappen "X beskeder" ud for hvert hold på vagtoversigten.

**Comment by MartinQwist** [comment]
Hvordan vil jeg som arrangør i denne løsning opdage, om der er kommet nye beskeder? Jeg kan se, at man kan gå ind på hvert hold og tjekke tidspunkterne for de seneste beskeder. Men der der andre måder? Fremhævning af nye beskeder eller lignende?

**Comment by mikkelsl** [comment]
Nej, det må vi lave senere. Men du kan se, at der er beskeder, og du kan deltage i chatten.

**Comment by MartinQwist** [comment]
OK. Jeg accepterer, og opretter nyt ønske om, at man kan se nye beskeder.
