### ISSUE TITLE
Eksport af liste over frivillige til event

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#54]
# Løser 34.1 i acceptkriterier

Flere af de første arrangører i Rehelper savner, at man som arrangør har mulighed for samlet liste over alle frivillige til et event på tværs af opgaver, vagter, dage og hold. 

I dag har man kun oversigter af hold - så hvis man opererer med flere hold, så har man ikke et samlet overblik. 

Behovet kan evt. løses ved, at arrangøren har adgang til en visning og/eller en eksport af alle frivillige tilmeldt et event.

Ønsker til information: 

- Skal ikke inkludere: email, medlemskab, sidst set
- Skal inkludere: Person, Telefon, Bopæl, Fødselsdag/alder, køn, T-shirt str., Nationalitet, Primært sprog, Taler, 
- Kan desuden inkludere: Antal vagter, antal frivilligtimer i alt, antal frivilligtimer seneste år.

**Comment by MartinQwist** [comment]
Eksporten inkluderer lige nu email adresser. Det skal den ikke på sigt. Men det er fint, at den gør det indtil videre, indtil vores andre kommunikationskanaler spiller 100%.

**Comment by mikkelsl** [comment]
Anton har lavet en liste med 2 tabs under "Se vagtplan" under "Vagter" på et event. Den kan både hentes for hele eventet og på de enkelte dage.

**Comment by MartinQwist** [comment]
Rigtig fin løsning. Den er accepteret. Vi fjerner mail fra oversigt og eksport, når vi synes, at de andre kommunikationskanaler spiller tilstrækkeligt
