### ISSUE TITLE
Tildeling af opgaver mellem gruppe og portal

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#60]
Pt. kan jeg oprette et event, oprette vagt og derefter fra gruppesiden udbyde vagerne eksklusivt for den gruppe. 

Jeg savner nu:
- At det bliver lidt tydligere, at og hvordan man flytter vagter tilbage til portalen. 1)at man får en feedback når man flytter en vagt tilbage til portalen "[vagtnavn] er flyttet til hovedportal" og 2)at der står et sted, at man skal klikke på vagterne for at flytte dem tilbage til hovedportalen.

**Comment by MartinQwist** [comment]
Løst med "Fjern eksklusivitet"_knap.
