### ISSUE TITLE
Udsendelse og besvarelse af spørgeskema

### ISSUE THREAD

**Issue by mikkelsl** [xooom-community/product#73]
- [x] #384
- [x] #385

# Løser 18.1 i acceptkriterier

Givet at jeg som frivillig har gennemført en vagt, når eventet er overstået, så vil jeg modtage en evaluering som jeg kan svare på og returnere.

# Løser 37 i acceptkriterier

Givet at jeg som arrangør eller admin har modtaget evalueringer, kan jeg gennemgå og sammenfatte feedback for at forbedre fremtidige events.

---

## Ønske

Rethinkers kan oprette en række standardspørgsmål
Arrangør kan oprette tillægsspørgsmål

Disse bliver automatisk sendt hver gang vagter på et event/vagter er overstået
Implementer udsendelse og besvarelse af spørgeskema

---

Obligatoriske låste spørgsmål for alle på Rehelper - gerne på tværs af alle licenser. Omk. 5 spørgsmål 
Arrangører har mulighed for at definere egne spørgsmål. evt. 3 spørgsmål.

![Image](https://github.com/xooom-community/product/assets/11291103/7518032a-46fd-47d0-8bb8-14e9e111a0fe)

![Image](https://github.com/xooom-community/product/assets/11291103/f8885e22-72e0-4f91-bc8d-184c4b1578b1)

**Comment by MartinQwist** [comment]
Kan nedprioriteres til fordel for Priority 1 i Volunteering.

**Comment by antonlund18** [comment]
@MartinQwist Jeg har udgivet den første version af spørgeskemaer til preview nu. Det ligger på sin egen side 'Spørgeskemaer' inde på dashboardet.

Jeg har lavet det så man kun kan have ét spørgeskema per frivilligorganisation / arrangør lige nu, med henblik på at udvide det senere. Når man har oprettet et spørgeskema, vil det automatisk blive sendt ud 2 dage efter sidste eventdato, til alle frivillige der havde en vagt på det event.

Når et spørgeskema bliver sendt ud, kan man ikke længere rette i det. Da kan man så i stedet oprette en ny version af spørgeskemaet, og vælge at gøre den version, som ens aktive version. Den version der er aktiv, er altså den der vil blive sendt ud automatisk.

Ekstra features:
- Se analyser for hver version af spørgeskemeat.
- Hver besvarelse er bundet op på et event. Derved kan man som arrangør også filtrere besvarelser per event.
- Distributionsstatus. Her kan man se hvor mange spørgeskemaet er blevet sendt ud til, hvor mange der har besvaret alle, nogle eller ingen af spørgsmålene. Kan også filtreres på version og event.

Der mangler stadig en måde at flette spørgeskemeaer fra organisation sammen med arrangørernes spørgeskema. Jeg får oprettet et nyt issue på dette.

**Comment by antonlund18** [comment]
https://github.com/orgs/xooom-community/projects/4/views/1?pane=issue&itemId=82464944

**Comment by MartinQwist** [comment]
Det ser godt ud. Jeg vil gerne vende den på vores møde i morgen.

**Comment by MartinQwist** [comment]
Jeg har stoppet den indtil arrnagørerne har mulighed for at fravælge udsendelsen af deres egne spørgsmål. (udsendelse af frivilligorganisationens spørgeskemaer vil altid være obligatorisk og følge en automatik).

**Comment by antonlund18** [comment]
@MartinQwist Jeg har opdateret spørgeskemaer nu, så arrangørernes spørgeskema bliver flettet sammen med spørgeskemaet fra frivilligorganisationen nu - og man kan også slå udsendelse til og fra for et spørgeskema. Forhåbentligt giver det bare mening, men du må sige til, hvis du har nogle spørgsmål.

**Comment by MartinQwist** [comment]
Vil I lige sige til, når denne deployes?

**Comment by antonlund18** [comment]
Det er ude nu 😊
